package uk.ac.man.cs.openphacts.queryexpander.queryLoader;

/**
 *
 * @author Christian
 */
public class Ops1_1QueryLoader extends QueryCaseLoader{
    
   public Ops1_1QueryLoader(){
       loadTargetPharma();
       loadTargetInfo();
       loadCompoundPharma();
       loadCompoundPharmacology();
       loadCompoundPharmacology_count();
       loadCoumpoundInfo();
       loadProteinInfo();
       loadProteinPharmacology_count();
       loadMarchCompound();
   } 
   
   private void loadTargetPharma() {
        QueryCase queryCase = new QueryCase();
        queryCase.key = "OpsTargetPharma";
        queryCase.name = "Ops Target Pharma Query";
        queryCase.originalQuery = "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX sio: <http://semanticscience.org/resource/>\n"
                + "PREFIX chemspider: <http://rdf.chemspider.com/#>\n"
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n"
                + "SELECT DISTINCT ?target_name ?smiles ?inchi ?inchi_key ?molweight ?num_ro5_violations ?std_type \n"
                + "                ?relation ?std_value ?std_unit ?target_organism\n"
                + "WHERE {\n"
                + "	GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "		<http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> skos:prefLabel ?target_name .\n"
                + "		?compound_cw skos:exactMatch ?csid_uri ; \n"
                + "			skos:prefLabel ?compound_name .\n"
                + "	}\n"
                + "	GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "		<http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> chembl:organism ?target_organism . \n"
                + "		?assay_uri chembl:hasTarget <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> .\n"
                + "		?activity_uri chembl:onAssay ?assay_uri ;\n"
                + "			chembl:type ?std_type ;\n"
                + "			chembl:relation ?relation ;\n"
                + "			chembl:standardValue ?std_value ;\n"
                + "			chembl:standardUnits ?std_unit ;\n"
                + "			chembl:forMolecule ?compound_uri .\n"
                + "		?csid_uri skos:exactMatch ?compound_uri .\n"
                + "		OPTIONAL { ?compound_uri sio:CHEMINF_000200 _:node1 . \n"
                + "			_:node1 a sio:CHEMINF_000314 ;\n"
                + "				sio:SIO_000300 ?num_ro5_violations }\n"
                + "		OPTIONAL { ?compound_uri sio:CHEMINF_000200 _:node2 . \n"
                + "			_:node2 a sio:CHEMINF_000198 ;\n"
                + "				sio:SIO_000300 ?molweight }\n"
                + "	}\n"
                + "	GRAPH <http://www.chemspider.com> {\n"
                + "		?csid_uri chemspider:smiles ?inchi;\n"
                + "			chemspider:inchikey ?inchi_key;\n"
                + "			chemspider:smiles ?smiles . \n"
                + "	}\n"
                + "}";             
        queryCase.replaceQuery = "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX sio: <http://semanticscience.org/resource/>\n"
                + "PREFIX chemspider: <http://rdf.chemspider.com/#>\n"
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n"
                + "SELECT DISTINCT ?target_name ?smiles ?inchi ?inchi_key ?molweight ?num_ro5_violations ?std_type \n"
                + "                ?relation ?std_value ?std_unit ?target_organism\n"
                + "WHERE {\n"
                + "	GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "		<http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> skos:prefLabel ?target_name .\n"
                + "		?compound_cw skos:exactMatch ?csid_uri ; \n"
                + "			skos:prefLabel ?compound_name .\n"
                + "	}\n"
                + "	GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "		?replacedURI1 chembl:organism ?target_organism . \n"
                + "		?assay_uri chembl:hasTarget ?replacedURI1 .\n"
                + "		?activity_uri chembl:onAssay ?assay_uri ;\n"
                + "			chembl:type ?std_type ;\n"
                + "			chembl:relation ?relation ;\n"
                + "			chembl:standardValue ?std_value ;\n"
                + "			chembl:standardUnits ?std_unit ;\n"
                + "			chembl:forMolecule ?compound_uri .\n"
                + "		?csid_uri skos:exactMatch ?compound_uri .\n"
                + "		OPTIONAL { ?compound_uri sio:CHEMINF_000200 _:node1 . \n"
                + "			_:node1 a sio:CHEMINF_000314 ;\n"
                + "				sio:SIO_000300 ?num_ro5_violations }\n"
                + "		OPTIONAL { ?compound_uri sio:CHEMINF_000200 _:node2 . \n"
                + "			_:node2 a sio:CHEMINF_000198 ;\n"
                + "				sio:SIO_000300 ?molweight }\n"
                + "     FILTER (?replacedURI1 = <http://data.kasabi.com/dataset/chembl-rdf/molecule/m276734> || \n"
                + "             ?replacedURI1 = <http://data.kasabi.com/dataset/chembl-rdf/target/t197>)"
                + "	}\n"
                + "	GRAPH <http://www.chemspider.com> {\n"
                + "		?csid_uri chemspider:smiles ?inchi;\n"
                + "			chemspider:inchikey ?inchi_key;\n"
                + "			chemspider:smiles ?smiles . \n"
                + "	}\n"
                + "}";             
        queries.put(queryCase.key, queryCase);
   }

   private void loadTargetInfo() {
        QueryCase queryCase = new QueryCase();
        queryCase.key = "OpsTargetInfo";
        queryCase.name = "Ops Target Info Query";
        queryCase.originalQuery = "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n"
                + "PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>\n"
                + "SELECT DISTINCT \n"
                + "   ?target_name ?target_type ?description ?organism \n"
                + "   (GROUP_CONCAT( DISTINCT ?keyword ; SEPARATOR=\" , \") as ?keywords )\n"
                + "   (GROUP_CONCAT( DISTINCT ?synonym ; SEPARATOR=\" , \" ) as ?synonyms)\n"
                + "   (GROUP_CONCAT( DISTINCT ?cellularLocation ; SEPARATOR=\" , \" ) as ?cellularLocations ) \n"
                + "   ?molecularWeight ?numberOfResidues ?pdbIdPage ?specificFunction ?theoreticalPi\n"
                + "WHERE {\n"
                + "	GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "		<http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> skos:prefLabel ?target_name.\n"
                + "	}\n"
                + "	GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "		<http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> chembl:hasKeyword ?keyword ;\n"
                + "			chembl:hasDescription ?description ;\n"
                + "			rdfs:subClassOf ?target_type ;\n"
                + "			chembl:organism ?organism ;\n"
                + "			rdfs:label ?synonym\n"
                + "	}\n"
                + "	GRAPH <http://linkedlifedata.com/resource/drugbank> {\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> drugbank:cellularLocation ?cellularLocation }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> drugbank:molecularWeight ?molecularWeight }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> drugbank:numberOfResidues ?numberOfResidues }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> drugbank:pdbIdPage ?pdbIdPage }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> drugbank:specificFunction ?specificFunction }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> drugbank:theoreticalPi ?theoreticalPi }\n"
                + "	}\n"
                + "}\n"
                + "GROUP BY ?target_name ?target_type ?description ?organism ?molecularWeight ?numberOfResidues \n"
                + "         ?pdbIdPage ?specificFunction ?theoreticalPi";
        //concat variables moved down
        //Singleton set added due to all optional
        queryCase.noReplaceQuery = "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n"
                + "PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>\n"
                + "SELECT DISTINCT \n"
                + "   ?target_name ?target_type ?description ?organism \n"
                + "   ?molecularWeight ?numberOfResidues ?pdbIdPage ?specificFunction ?theoreticalPi\n"
                + "   (GROUP_CONCAT( DISTINCT ?keyword ; SEPARATOR=\" , \") as ?keywords )\n"
                + "   (GROUP_CONCAT( DISTINCT ?synonym ; SEPARATOR=\" , \" ) as ?synonyms)\n"
                + "   (GROUP_CONCAT( DISTINCT ?cellularLocation ; SEPARATOR=\" , \" ) as ?cellularLocations ) \n"
                + "WHERE {\n"
                + "	GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "		<http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> skos:prefLabel ?target_name.\n"
                + "	}\n"
                + "	GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "		<http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> chembl:hasKeyword ?keyword ;\n"
                + "			chembl:hasDescription ?description ;\n"
                + "			rdfs:subClassOf ?target_type ;\n"
                + "			chembl:organism ?organism ;\n"
                + "			rdfs:label ?synonym\n"
                + "	}\n"
                + "{}"
                + "	GRAPH <http://linkedlifedata.com/resource/drugbank> {\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> drugbank:cellularLocation ?cellularLocation }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> drugbank:molecularWeight ?molecularWeight }\n"
                + "		OPTIONAL { http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> drugbank:numberOfResidues ?numberOfResidues }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> drugbank:pdbIdPage ?pdbIdPage }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> drugbank:specificFunction ?specificFunction }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> drugbank:theoreticalPi ?theoreticalPi }\n"
                + "	}\n"
                + "}\n"
                + "GROUP BY ?target_name ?target_type ?description ?organism ?molecularWeight ?numberOfResidues \n"
                + "         ?pdbIdPage ?specificFunction ?theoreticalPi";
        queryCase.replaceQuery = "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n"
                + "PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>\n"
                + "SELECT DISTINCT \n"
                + "   ?target_name ?target_type ?description ?organism \n"
                + "   ?molecularWeight ?numberOfResidues ?pdbIdPage ?specificFunction ?theoreticalPi\n"
                + "   (GROUP_CONCAT( DISTINCT ?keyword ; SEPARATOR=\" , \") as ?keywords )\n"
                + "   (GROUP_CONCAT( DISTINCT ?synonym ; SEPARATOR=\" , \" ) as ?synonyms)\n"
                + "   (GROUP_CONCAT( DISTINCT ?cellularLocation ; SEPARATOR=\" , \" ) as ?cellularLocations ) \n"
                + "WHERE {\n"
                + "	GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "		<http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> skos:prefLabel ?target_name.\n"
                + "	}\n"
                + "	GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "		?replacedURI1 chembl:hasKeyword ?keyword ;\n"
                + "			chembl:hasDescription ?description ;\n"
                + "			rdfs:subClassOf ?target_type ;\n"
                + "			chembl:organism ?organism ;\n"
                + "			rdfs:label ?synonym\n"
                + "     FILTER (?replacedURI1 = <http://data.kasabi.com/dataset/chembl-rdf/molecule/m276734> || \n"
                + "             ?replacedURI1 = <http://data.kasabi.com/dataset/chembl-rdf/target/t197>)"
                + "	}\n"
                + "{}"
                + "	GRAPH <http://linkedlifedata.com/resource/drugbank> {\n"
                + "		OPTIONAL { ?replacedURI2 drugbank:cellularLocation ?cellularLocation }\n"
                + "		OPTIONAL { ?replacedURI2 drugbank:molecularWeight ?molecularWeight }\n"
                + "		OPTIONAL { ?replacedURI2 drugbank:numberOfResidues ?numberOfResidues }\n"
                + "		OPTIONAL { ?replacedURI2 drugbank:pdbIdPage ?pdbIdPage }\n"
                + "		OPTIONAL { ?replacedURI2 drugbank:specificFunction ?specificFunction }\n"
                + "		OPTIONAL { ?replacedURI2 drugbank:theoreticalPi ?theoreticalPi }\n"
                + "     FILTER (?replacedURI2 = <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugs/DB00398> ||\n"
                + "             ?replacedURI2 = <http://www4.wiwiss.fu-berlin.de/drugbank/resource/targets/228>)\n"
                + "	}\n"
                + "}\n"
                + "GROUP BY ?target_name ?target_type ?description ?organism ?molecularWeight ?numberOfResidues \n"
                + "         ?pdbIdPage ?specificFunction ?theoreticalPi";
        queries.put(queryCase.key, queryCase);
   }

   private void loadCompoundPharma() {
        QueryCase queryCase = new QueryCase();
        queryCase.key = "OpsCompoundPharma";
        queryCase.name = "Ops Compound Pharma Query";
        queryCase.originalQuery = "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX chemspider: <http://rdf.chemspider.com/#>\n"
                + "PREFIX sio: <http://semanticscience.org/resource/>\n"
                + "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX dc: <http://purl.org/dc/elements/1.1/>\n"
                + "SELECT ?compound_name ?target_name ?csid_uri ?smiles ?inchi ?inchi_key ?molweight \n"
                + "       ?num_ro5_violations ?std_type ?relation ?std_value ?std_unit ?target_organism\n"
                + "WHERE {\n"
                + "	GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "		<http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> skos:prefLabel ?compound_name.\n"
                + "	}\n"
                + "	GRAPH <http://www.chemspider.com> {\n"
                + "		<http://rdf.chemspider.com/187440>  chemspider:smiles ?inchi;\n"
                + "			chemspider:inchikey ?inchi_key;\n"
                + "			chemspider:smiles ?smiles . \n"
                + "		?csid_uri chemspider:inchikey ?inchi_key .\n"
                + "	}\n"
                + "	GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "		?activity_uri chembl:forMolecule <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> ;\n"
                + "			          chembl:type ?std_type ;\n"
                + "                   chembl:relation ?relation ;\n"
                + "                   chembl:standardValue ?std_value ;\n"
                + "                   chembl:standardUnits ?std_unit ;\n"
                + "                   chembl:onAssay ?assay_uri .\n"
                + "     ?assay_uri chembl:hasTarget ?target_uri .\n"
                + "		?target_uri dc:title ?target_name ;\n"
                + "                 chembl:organism ?target_organism .\n"
                + "		OPTIONAL { \n"
                + "         <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> sio:CHEMINF_000200 _:node1 . \n"
                + "			_:node1 a sio:CHEMINF_000314 ;\n"
                + "			    	sio:SIO_000300 ?num_ro5_violations \n"
                + "     }\n"
                + "		OPTIONAL { \n"
                + "         <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> sio:CHEMINF_000200 _:node2 . \n"
                + "			_:node2 a sio:CHEMINF_000198 ;\n"
                + "			        sio:SIO_000300 ?molweight \n"
                + "     }\n"
                + "	}\n"
                + "}";
        queryCase.replaceQuery = "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX chemspider: <http://rdf.chemspider.com/#>\n"
                + "PREFIX sio: <http://semanticscience.org/resource/>\n"
                + "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX dc: <http://purl.org/dc/elements/1.1/>\n"
                + "SELECT ?compound_name ?target_name ?csid_uri ?smiles ?inchi ?inchi_key ?molweight \n"
                + "       ?num_ro5_violations ?std_type ?relation ?std_value ?std_unit ?target_organism\n"
                + "WHERE {\n"
                + "	GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "		<http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> skos:prefLabel ?compound_name.\n"
                + "	}\n"
                + "	GRAPH <http://www.chemspider.com> {\n"
                + "		<http://rdf.chemspider.com/187440>  chemspider:smiles ?inchi;\n"
                + "			chemspider:inchikey ?inchi_key;\n"
                + "			chemspider:smiles ?smiles . \n"
                + "		?csid_uri chemspider:inchikey ?inchi_key .\n"
                + "	}\n"
                + "	GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "		?activity_uri chembl:forMolecule ?replacedURI1 ;\n"
                + "			          chembl:type ?std_type ;\n"
                + "                   chembl:relation ?relation ;\n"
                + "                   chembl:standardValue ?std_value ;\n"
                + "                   chembl:standardUnits ?std_unit ;\n"
                + "                   chembl:onAssay ?assay_uri .\n"
                + "     ?assay_uri chembl:hasTarget ?target_uri .\n"
                + "		?target_uri dc:title ?target_name ;\n"
                + "                 chembl:organism ?target_organism .\n"
                + "		OPTIONAL { \n"
                + "         ?replacedURI1 sio:CHEMINF_000200 _:node1 . \n"
                + "			_:node1 a sio:CHEMINF_000314 ;\n"
                + "			    	sio:SIO_000300 ?num_ro5_violations \n"
                + "     }\n"
                + "		OPTIONAL { \n"
                + "         ?replacedURI1 sio:CHEMINF_000200 _:node2 . \n"
                + "			_:node2 a sio:CHEMINF_000198 ;\n"
                + "			        sio:SIO_000300 ?molweight \n"
                + "     }\n"
                + "     FILTER (?replacedURI1 = <http://data.kasabi.com/dataset/chembl-rdf/molecule/m276734> || \n"
                + "             ?replacedURI1 = <http://data.kasabi.com/dataset/chembl-rdf/target/t197>)"
                 + "	}\n"
                + "}";
        queries.put(queryCase.key, queryCase);
    }
   
   private void loadCompoundPharmacology() {
        QueryCase queryCase = new QueryCase();
        queryCase.key = "OpsCompoundPharmacology";
        queryCase.name = "Ops Compound Pharmacology Query";
        queryCase.originalQuery = "SELECT ?compound_name ?target_name ?csid_uri ?smiles ?inchi ?inchiKey ?molweight \n"
                + "  ?num_ro5_violations ?std_type ?relation ?std_value ?std_unit ?assay_organism \n"
                + "WHERE {\n"
                + "  GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "    <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> \n"
                + "      <http://www.w3.org/2004/02/skos/core#prefLabel> ?compound_name.\n"
                + "  }\n"
                + "  GRAPH <http://www.chemspider.com> {\n"
                + "    <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> \n"
                + "      <http://rdf.chemspider.com/#smiles> ?smiles.\n"
                + "    <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> \n"
                + "      <http://rdf.chemspider.com/#inchi> ?inchi.\n"
                + "    <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> \n"
                + "      <http://rdf.chemspider.com/#inchikey> ?inchiKey.\n"
                + "    ?csid_uri <http://rdf.chemspider.com/#inchi> ?inchi.\n"
                + "  }"
                + "  GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "    ?activity_uri <http://rdf.farmbio.uu.se/chembl/onto/#forMolecule> \n"
                + "         <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5>;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#type> ?std_type;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#relation> ?relation;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#standardValue> ?std_value;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#standardUnits> ?std_unit;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#onAssay> ?assay_uri . \n"
                + "    ?assay_uri <http://rdf.farmbio.uu.se/chembl/onto/#hasTarget> ?target_uri . \n"
                + "    ?target_uri <http://purl.org/dc/elements/1.1/title> ?target_name .\n"
                + "    ?target_uri <http://rdf.farmbio.uu.se/chembl/onto/#organism> ?assay_organism . \n"
                + "    OPTIONAL { "
                + "      <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5>\n"
                + "          <http://semanticscience.org/resource/CHEMINF_000200> _:bNode1 . \n"
                + "      _:bNode1 a <http://semanticscience.org/resource/CHEMINF_000314> ;\n"
                + "               <http://semanticscience.org/resource/SIO_000300> ?num_ro5_violations.\n"
                + "    }"
                + "    OPTIONAL {"
                + "       <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5>\n"
                + "           <http://semanticscience.org/resource/CHEMINF_000200> _:bNode2 . \n"
                + "       _:bNode2 a <http://semanticscience.org/resource/CHEMINF_000198> ;\n"
                + "                <http://semanticscience.org/resource/SIO_000300> ?molweight. \n"
                + "    }"
                + "  }"
                + "  OPTIONAL {\n "
                + "    GRAPH <http://linkedlifedata.com/resource/drugbank> {\n"
                + "      <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> \n"
                + "          <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/affectedOrganism> ?affectedOrganism. \n"
                + "      OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> \n"
                + "          <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/biotransformation> ?biotransformation. }\n"
                + "      OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> \n"
                + "          <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/description> ?description.}\n"
                + "      OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> \n"
                + "          <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/indication> ?indication.}\n"
                + "      OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> \n"
                + "          <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/proteinBinding> ?proteinBinding.}\n"
                + "      OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> \n"
                + "          <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/toxicity> ?toxicity.}\n"
                + "      OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> \n"
                + "          <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/meltingPoint> ?meltingPoint.}\n"
                + "    }\n"
                + "  }\n"
                + "}";
        queryCase.replaceQuery = "SELECT ?compound_name ?target_name ?csid_uri ?smiles ?inchi ?inchiKey ?molweight \n"
                + "  ?num_ro5_violations ?std_type ?relation ?std_value ?std_unit ?assay_organism \n"
                + "WHERE {\n"
                + "  GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "    <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> \n"
                + "      <http://www.w3.org/2004/02/skos/core#prefLabel> ?compound_name.\n"
                + "  }\n"
                + "  GRAPH <http://www.chemspider.com> {\n"
                + "    <http://rdf.chemspider.com/187440> <http://rdf.chemspider.com/#smiles> ?smiles.\n"
                + "    <http://rdf.chemspider.com/187440> <http://rdf.chemspider.com/#inchi> ?inchi.\n"
                + "    <http://rdf.chemspider.com/187440> <http://rdf.chemspider.com/#inchikey> ?inchiKey.\n"
                + "    ?csid_uri <http://rdf.chemspider.com/#inchi> ?inchi.\n"
                + "  }"
                + "  GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "    ?activity_uri <http://rdf.farmbio.uu.se/chembl/onto/#forMolecule> ?replacedURI1;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#type> ?std_type;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#relation> ?relation;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#standardValue> ?std_value;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#standardUnits> ?std_unit;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#onAssay> ?assay_uri . \n"
                + "    ?assay_uri <http://rdf.farmbio.uu.se/chembl/onto/#hasTarget> ?target_uri . \n"
                + "    ?target_uri <http://purl.org/dc/elements/1.1/title> ?target_name .\n"
                + "    ?target_uri <http://rdf.farmbio.uu.se/chembl/onto/#organism> ?assay_organism . \n"
                + "    OPTIONAL { "
                + "      ?replacedURI1 <http://semanticscience.org/resource/CHEMINF_000200> _:bNode1 . \n"
                + "      _:bNode1 a <http://semanticscience.org/resource/CHEMINF_000314> ;\n"
                + "               <http://semanticscience.org/resource/SIO_000300> ?num_ro5_violations.\n"
                + "    }"
                + "    OPTIONAL {"
                + "       ?replacedURI1 <http://semanticscience.org/resource/CHEMINF_000200> _:bNode2 . \n"
                + "       _:bNode2 a <http://semanticscience.org/resource/CHEMINF_000198> ;\n"
                + "                <http://semanticscience.org/resource/SIO_000300> ?molweight. \n"
                + "    }"
                + "    FILTER (?replacedURI1 = <http://data.kasabi.com/dataset/chembl-rdf/molecule/m276734> \n"
                + "         || ?replacedURI1 =  <http://data.kasabi.com/dataset/chembl-rdf/target/t197>)\n"
                + "  }"
                + "  OPTIONAL {\n "
                + "    GRAPH <http://linkedlifedata.com/resource/drugbank> {\n"
                + "      ?replacedURI2 <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/affectedOrganism> ?affectedOrganism. \n"
                + "      OPTIONAL { ?replacedURI2 <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/biotransformation> ?biotransformation. }\n"
                + "      OPTIONAL { ?replacedURI2 <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/description> ?description.}\n"
                + "      OPTIONAL { ?replacedURI2 <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/indication> ?indication.}\n"
                + "      OPTIONAL { ?replacedURI2 <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/proteinBinding> ?proteinBinding.}\n"
                + "      OPTIONAL { ?replacedURI2 <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/toxicity> ?toxicity.}\n"
                + "      OPTIONAL { ?replacedURI2 <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/meltingPoint> ?meltingPoint.}\n"
                + "      FILTER (?replacedURI2 = <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugs/DB00398> \n"
                + "           || ?replacedURI2 = <http://www4.wiwiss.fu-berlin.de/drugbank/resource/targets/228>)\n"
                + "    }\n"
                + "  }\n"
                + "}";
        queries.put(queryCase.key, queryCase);
   }

   private void loadCoumpoundInfo() {
        QueryCase queryCase = new QueryCase();
        queryCase.key = "OpsCoumpoundInfo";
        queryCase.name = "Ops CoumpoundInfo Query";
        queryCase.originalQuery = "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX chemspider: <http://rdf.chemspider.com/#>\n"
                + "PREFIX sio: <http://semanticscience.org/resource/>\n"
                + "PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>\n"
                + "SELECT DISTINCT ?compound_name ?csid_uri ?molformula ?molweight ?inchi ?inchi_key ?smiles ?alogp "
                + "                ?hba ?hbd ?mw_freebase ?num_ro5_violations ?psa ?rtb ?meltingPoint ?affectedOrganism "
                + "                ?biotransformation ?description ?indication ?proteinBinding ?toxicity\n"
                + "WHERE {\n"
                + "	GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "		<http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> skos:prefLabel ?compound_name.\n"
                + "	}\n"
                + "	GRAPH <http://www.chemspider.com> {\n"
                + "		<http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5>  chemspider:smiles ?inchi;\n"
                + "			chemspider:inchikey ?inchi_key;\n"
                + "			chemspider:smiles ?smiles . \n"
                + "		?csid_uri chemspider:inchikey ?inchi_key .\n"
                + "	}\n"
                + "	GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "		<http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> sio:CHEMINF_000200 _:node1 . \n"
                + "		_:node1 a sio:CHEMINF_000042 ;\n"
                + "			sio:SIO_000300 ?molformula\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> sio:CHEMINF_000200 _:node2 . \n"
                + "			_:node2 a sio:CHEMINF_000305 ;\n"
                + "				sio:SIO_000300 ?alogp }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> sio:CHEMINF_000200 _:node3 . \n"
                + "			_:node3 a sio:CHEMINF_000309 ;\n"
                + "				sio:SIO_000300 ?hba }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> sio:CHEMINF_000200 _:node4 . \n"
                + "			_:node4 a sio:CHEMINF_000310 ;\n"
                + "				sio:SIO_000300 ?hbd }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> sio:CHEMINF_000200 _:node5 . \n"
                + "			_:node5 a sio:CHEMINF_000198 ;\n"
                + "				sio:SIO_000300 ?molweight }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> sio:CHEMINF_000200 _:node6 . \n"
                + "			_:node6 a sio:CHEMINF_000350 ;\n"
                + "				sio:SIO_000300 ?mw_freebase }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> sio:CHEMINF_000200 _:node7 . \n"
                + "			_:node7 a sio:CHEMINF_000314 ;\n"
                + "				sio:SIO_000300 ?num_ro5_violations }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> sio:CHEMINF_000200 _:node8 . \n"
                + "			_:node8 a sio:CHEMINF_000308 ;\n"
                + "				sio:SIO_000300 ?psa }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> sio:CHEMINF_000200 _:node9 . \n"
                + "			_:node9 a sio:CHEMINF_000311 ;\n"
                + "				sio:SIO_000300 ?rtb }\n"
                + "	}\n"
                + "	GRAPH <http://linkedlifedata.com/resource/drugbank> {\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> drugbank:affectedOrganism ?affectedOrganism }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> drugbank:biotransformation ?biotransformation }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> drugbank:description ?description }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> drugbank:indication ?indication }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> drugbank:proteinBinding ?proteinBinding }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> drugbank:toxicity ?toxicity }\n"
                + "		OPTIONAL { <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> drugbank:meltingPoint ?meltingPoint }\n"
                + "	}\n"
                + "}";
        //Singleton set added due to all optional
        queryCase.replaceQuery = "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX chemspider: <http://rdf.chemspider.com/#>\n"
                + "PREFIX sio: <http://semanticscience.org/resource/>\n"
                + "PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>\n"
                + "SELECT DISTINCT ?compound_name ?csid_uri ?molformula ?molweight ?inchi ?inchi_key ?smiles ?alogp "
                + "                ?hba ?hbd ?mw_freebase ?num_ro5_violations ?psa ?rtb ?meltingPoint ?affectedOrganism "
                + "                ?biotransformation ?description ?indication ?proteinBinding ?toxicity\n"
                + "WHERE {\n"
                + "	GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "		<http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> skos:prefLabel ?compound_name.\n"
                + "	}\n"
                + "	GRAPH <http://www.chemspider.com> {\n"
                + "		<http://rdf.chemspider.com/187440>  chemspider:smiles ?inchi;\n"
                + "			chemspider:inchikey ?inchi_key;\n"
                + "			chemspider:smiles ?smiles . \n"
                + "		?csid_uri chemspider:inchikey ?inchi_key .\n"
                + "	}\n"
                + "	GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "		?replacedURI1 sio:CHEMINF_000200 _:node1 . \n"
                + "		_:node1 a sio:CHEMINF_000042 ;\n"
                + "			sio:SIO_000300 ?molformula\n"
                + "		OPTIONAL { ?replacedURI1 sio:CHEMINF_000200 _:node2 . \n"
                + "			_:node2 a sio:CHEMINF_000305 ;\n"
                + "				sio:SIO_000300 ?alogp }\n"
                + "		OPTIONAL { ?replacedURI1 sio:CHEMINF_000200 _:node3 . \n"
                + "			_:node3 a sio:CHEMINF_000309 ;\n"
                + "				sio:SIO_000300 ?hba }\n"
                + "		OPTIONAL { ?replacedURI1 sio:CHEMINF_000200 _:node4 . \n"
                + "			_:node4 a sio:CHEMINF_000310 ;\n"
                + "				sio:SIO_000300 ?hbd }\n"
                + "		OPTIONAL { ?replacedURI1 sio:CHEMINF_000200 _:node5 . \n"
                + "			_:node5 a sio:CHEMINF_000198 ;\n"
                + "				sio:SIO_000300 ?molweight }\n"
                + "		OPTIONAL { ?replacedURI1 sio:CHEMINF_000200 _:node6 . \n"
                + "			_:node6 a sio:CHEMINF_000350 ;\n"
                + "				sio:SIO_000300 ?mw_freebase }\n"
                + "		OPTIONAL { ?replacedURI1 sio:CHEMINF_000200 _:node7 . \n"
                + "			_:node7 a sio:CHEMINF_000314 ;\n"
                + "				sio:SIO_000300 ?num_ro5_violations }\n"
                + "		OPTIONAL { ?replacedURI1 sio:CHEMINF_000200 _:node8 . \n"
                + "			_:node8 a sio:CHEMINF_000308 ;\n"
                + "				sio:SIO_000300 ?psa }\n"
                + "		OPTIONAL { ?replacedURI1 sio:CHEMINF_000200 _:node9 . \n"
                + "			_:node9 a sio:CHEMINF_000311 ;\n"
                + "				sio:SIO_000300 ?rtb }\n"
                + "     FILTER (?replacedURI1 = <http://data.kasabi.com/dataset/chembl-rdf/molecule/m276734> || \n"
                + "             ?replacedURI1 = <http://data.kasabi.com/dataset/chembl-rdf/target/t197>)"
                + "	}\n"
                + " {}"
                + "	GRAPH <http://linkedlifedata.com/resource/drugbank> {\n"
                + "		OPTIONAL { ?replacedURI2 drugbank:affectedOrganism ?affectedOrganism }\n"
                + "		OPTIONAL { ?replacedURI2 drugbank:biotransformation ?biotransformation }\n"
                + "		OPTIONAL { ?replacedURI2 drugbank:description ?description }\n"
                + "		OPTIONAL { ?replacedURI2 drugbank:indication ?indication }\n"
                + "		OPTIONAL { ?replacedURI2 drugbank:proteinBinding ?proteinBinding }\n"
                + "		OPTIONAL { ?replacedURI2 drugbank:toxicity ?toxicity }\n"
                + "		OPTIONAL { ?replacedURI2 drugbank:meltingPoint ?meltingPoint }\n"
                + "     FILTER (?replacedURI2 = <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugs/DB00398> ||\n"
                + "             ?replacedURI2 = <http://www4.wiwiss.fu-berlin.de/drugbank/resource/targets/228>)\n"
                + "	}\n"
                + "}";
        queries.put(queryCase.key, queryCase);
   }

   private void loadMarchCompound() {
        QueryCase queryCase = new QueryCase();
        queryCase.key = "Ops";
        queryCase.name = "Ops Query March Compound Query ";
        queryCase.originalQuery = "PREFIX c2b2r_chembl: <http://chem2bio2rdf.org/chembl/resource/>\n"
                + "PREFIX chemspider: <http://rdf.chemspider.com/#> \n"
                + "PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>\n"
                + "PREFIX farmbio: <http://rdf.farmbio.uu.se/chembl/onto/#> \n"
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> \n"
                + "PREFIX skos: <http://www.w3.org/2004/02/skos/core#> \n"
                + "SELECT DISTINCT ?target_name ?compound_name ?csid_uri ?smiles ?inchi ?inchiKey ?molweight \n"
                + "                ?num_ro5_violations ?std_type ?relation ?std_value ?std_unites ?assay_organism \n"
                + "WHERE { \n"
                + "  GRAPH <http://www.chem2bio2rdf.org/ChEMBL> { \n"
                + "    ?assay2target_uri c2b2r_chembl:tid   <http://www.conceptwiki.org/concept/458eaa59-79a5-448f-9085-9664f6f643af> ; \n"
                + "                      c2b2r_chembl:assay_id ?assay_uri ; \n"
                + "                      c2b2r_chembl:assay_organism ?assay_organism . \n"
                + "    ?activity_uri farmbio:onAssay ?assay_uri ;  \n"
                + "                  c2b2r_chembl:c2b2r_chembl_02_activities_molregno ?compound_uri ; \n"
                + "                  c2b2r_chembl:std_type ?std_type ; \n"
                + "                  c2b2r_chembl:relation ?relation ; \n"
                + "                  c2b2r_chembl:std_value ?std_value ; \n"
                + "                  c2b2r_chembl:std_unites ?std_unites . \n"
                + "    ?csid_uri skos:exactMatch ?compound_uri \n"
                + "    OPTIONAL { ?compound_uri c2b2r_chembl:molweight ?molweight } \n"
                + "    OPTIONAL { ?compound_uri c2b2r_chembl:num_ro5_violations ?num_ro5_violations } \n"
                + "    OPTIONAL { ?compound_uri c2b2r_chembl:canonical_smiles ?smiles } \n"
                + "    OPTIONAL { ?compound_uri c2b2r_chembl:inchi ?inchi } \n "
                + "    OPTIONAL { ?compound_uri c2b2r_chembl:inchi_key ?inchiKey }\n"
                + "  } \n"
                + "  GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "    <http://www.conceptwiki.org/concept/458eaa59-79a5-448f-9085-9664f6f643af> skos:prefLabel ?target_name . \n"
                + "    ?compound_cw skos:exactMatch ?csid_uri ; skos:prefLabel ?compound_name \n"
                + "  }\n"
                + "} LIMIT 100";
        queryCase.textReplaceQuery = "PREFIX c2b2r_chembl: <http://chem2bio2rdf.org/chembl/resource/>\n"
                + "PREFIX chemspider: <http://rdf.chemspider.com/#> \n"
                + "PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>\n"
                + "PREFIX farmbio: <http://rdf.farmbio.uu.se/chembl/onto/#> \n"
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> \n"
                + "PREFIX skos: <http://www.w3.org/2004/02/skos/core#> \n"
                + "SELECT DISTINCT ?target_name ?compound_name ?csid_uri ?smiles ?inchi ?inchiKey ?molweight \n"
                + "                ?num_ro5_violations ?std_type ?relation ?std_value ?std_unites ?assay_organism \n"
                + "WHERE { \n"
                + "  GRAPH <http://www.chem2bio2rdf.org/ChEMBL> { \n"
                + "    ?assay2target_uri c2b2r_chembl:tid <http://www.conceptwiki.org/concept/458eaa59-79a5-448f-9085-9664f6f643af> ; \n"
                + "                      c2b2r_chembl:assay_id ?assay_uri ; \n"
                + "                      c2b2r_chembl:assay_organism ?assay_organism . \n"
                + "    ?activity_uri farmbio:onAssay ?assay_uri ;  \n"
                + "                  c2b2r_chembl:c2b2r_chembl_02_activities_molregno ?compound_uri ; \n"
                + "                  c2b2r_chembl:std_type ?std_type ; \n"
                + "                  c2b2r_chembl:relation ?relation ; \n"
                + "                  c2b2r_chembl:std_value ?std_value ; \n"
                + "                  c2b2r_chembl:std_unites ?std_unites . \n"
                + "    ?csid_uri skos:exactMatch ?compound_uri \n"
                + "    OPTIONAL { ?compound_uri c2b2r_chembl:molweight ?molweight } \n"
                + "    OPTIONAL { ?compound_uri c2b2r_chembl:num_ro5_violations ?num_ro5_violations } \n"
                + "    OPTIONAL { ?compound_uri c2b2r_chembl:canonical_smiles ?smiles } \n"
                + "    OPTIONAL { ?compound_uri c2b2r_chembl:inchi ?inchi } \n "
                + "    OPTIONAL { ?compound_uri c2b2r_chembl:inchi_key ?inchiKey }\n"
                + "  } \n"
                + "  GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "    <http://www.conceptwiki.org/concept/458eaa59-79a5-448f-9085-9664f6f643af> skos:prefLabel ?target_name . \n"
                + "    ?compound_cw skos:exactMatch ?csid_uri ; skos:prefLabel ?compound_name \n"
                + "  }\n"
                + "} LIMIT 100";
        queryCase.serverReplaceQuery = "PREFIX c2b2r_chembl: <http://chem2bio2rdf.org/chembl/resource/>\n"
                + "PREFIX chemspider: <http://rdf.chemspider.com/#> \n"
                + "PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>\n"
                + "PREFIX farmbio: <http://rdf.farmbio.uu.se/chembl/onto/#> \n"
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> \n"
                + "PREFIX skos: <http://www.w3.org/2004/02/skos/core#> \n"
                + "SELECT DISTINCT ?target_name ?compound_name ?csid_uri ?smiles ?inchi ?inchiKey ?molweight \n"
                + "                ?num_ro5_violations ?std_type ?relation ?std_value ?std_unites ?assay_organism \n"
                + "WHERE { \n"
                + "  GRAPH <http://www.chem2bio2rdf.org/ChEMBL> { \n"
                + "    ?assay2target_uri c2b2r_chembl:tid <http://www4.wiwiss.fu-berlin.de/drugbank/resource/targets/6292> ; \n"
                + "                      c2b2r_chembl:assay_id ?assay_uri ; \n"
                + "                      c2b2r_chembl:assay_organism ?assay_organism . \n"
                + "    ?activity_uri farmbio:onAssay ?assay_uri ;  \n"
                + "                  c2b2r_chembl:c2b2r_chembl_02_activities_molregno ?compound_uri ; \n"
                + "                  c2b2r_chembl:std_type ?std_type ; \n"
                + "                  c2b2r_chembl:relation ?relation ; \n"
                + "                  c2b2r_chembl:std_value ?std_value ; \n"
                + "                  c2b2r_chembl:std_unites ?std_unites . \n"
                + "    ?csid_uri skos:exactMatch ?compound_uri \n"
                + "    OPTIONAL { ?compound_uri c2b2r_chembl:molweight ?molweight } \n"
                + "    OPTIONAL { ?compound_uri c2b2r_chembl:num_ro5_violations ?num_ro5_violations } \n"
                + "    OPTIONAL { ?compound_uri c2b2r_chembl:canonical_smiles ?smiles } \n"
                + "    OPTIONAL { ?compound_uri c2b2r_chembl:inchi ?inchi } \n "
                + "    OPTIONAL { ?compound_uri c2b2r_chembl:inchi_key ?inchiKey }\n"
                + "  } \n"
                + "  GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "    <http://www.conceptwiki.org/concept/458eaa59-79a5-448f-9085-9664f6f643af> skos:prefLabel ?target_name . \n"
                + "    ?compound_cw skos:exactMatch ?csid_uri ; skos:prefLabel ?compound_name \n"
                + "  }\n"
                + "} LIMIT 100";
       queries.put(queryCase.key, queryCase);
   }

   private void loadProteinInfo() {
        QueryCase queryCase = new QueryCase();
        queryCase.key = "OpsProteinInfo";
        queryCase.name = "Ops Protein Info Query";
        queryCase.originalQuery = "SELECT DISTINCT ?target_name ?target_type ?description ?organism \n"
                + "(GROUP_CONCAT( DISTINCT ?keyword ; SEPARATOR=\" , \") as ?keywords ) \n"
                + "(GROUP_CONCAT( DISTINCT ?synonym ; SEPARATOR=\" , \" ) as ?synonyms) \n"
                + "(GROUP_CONCAT( DISTINCT ?cellularLocation ; SEPARATOR=\" , \" ) as ?cellularLocations ) \n"
                + "?molecularWeight ?numberOfResidues ?pdbIdPage ?specificFunction ?theoreticalPi\n"
                + "WHERE {\n"
                + "  GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "    <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0> \n"
                + "      <http://www.w3.org/2004/02/skos/core#prefLabel> ?target_name."
                + "  }\n"
                + "  GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "    <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0> \n"
                + "       <http://rdf.farmbio.uu.se/chembl/onto/#hasKeyword> ?keyword.\n"
                + "    <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0> \n"
                + "       <http://rdf.farmbio.uu.se/chembl/onto/#hasDescription> ?description.\n"
                + "    <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0> \n"
                + "       <http://www.w3.org/2000/01/rdf-schema#subClassOf> ?target_type.\n"
                + "    <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0> \n"
                + "       <http://rdf.farmbio.uu.se/chembl/onto/#organism> ?organism.\n"
                + "    <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0> \n"
                + "       <http://www.w3.org/2000/01/rdf-schema#label> ?synonym.\n"
                + "  }\n"
                + "  OPTIONAL {\n"
                + "    GRAPH <http://linkedlifedata.com/resource/drugbank> {\n"
                + "      OPTIONAL { <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0>\n"
                + "        <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/cellularLocation> ?cellularLocation. }\n"
                + "      OPTIONAL { <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0>\n"
                + "        <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/molecularWeight> ?molecularWeight.}\n"
                + "      OPTIONAL { <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0>\n"
                + "        <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/numberOfResidues> ?numberOfResidues . }\n"
                + "      OPTIONAL { <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0>\n"
                + "        <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/pdbIdPage> ?pdbIdPage . }\n"
                + "      OPTIONAL { <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0>\n"
                + "        <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/specificFunction> ?specificFunction .}  \n"
                + "      OPTIONAL { <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0>\n"
                + "        <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/theoreticalPi> ?theoreticalPi .}\n"
               + "    }"
                + "  }\n"
                + "}\n"
                + "GROUP BY ?target_name ?target_type ?description ?organism ?molecularWeight ?numberOfResidues ?pdbIdPage \n"
                + "         ?specificFunction ?theoreticalPi";
        queryCase.replaceQuery = "SELECT DISTINCT ?target_name ?target_type ?description ?organism \n"
                + "?molecularWeight ?numberOfResidues ?pdbIdPage ?specificFunction ?theoreticalPi\n"
                + "(GROUP_CONCAT( DISTINCT ?keyword ; SEPARATOR=\" , \") as ?keywords ) \n"
                + "(GROUP_CONCAT( DISTINCT ?synonym ; SEPARATOR=\" , \" ) as ?synonyms) \n"
                + "(GROUP_CONCAT( DISTINCT ?cellularLocation ; SEPARATOR=\" , \" ) as ?cellularLocations ) \n"
                + "WHERE {\n"
                + "  GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "    <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0> \n"
                + "      <http://www.w3.org/2004/02/skos/core#prefLabel> ?target_name."
                + "  }\n"
                + "  GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "    <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0> \n"
                + "       <http://rdf.farmbio.uu.se/chembl/onto/#hasKeyword> ?keyword.\n"
                + "    <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0> \n"
                + "       <http://rdf.farmbio.uu.se/chembl/onto/#hasDescription> ?description.\n"
                + "    <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0> \n"
                + "       <http://www.w3.org/2000/01/rdf-schema#subClassOf> ?target_type.\n"
                + "    <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0> \n"
                + "       <http://rdf.farmbio.uu.se/chembl/onto/#organism> ?organism.\n"
                + "    <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0> \n"
                + "       <http://www.w3.org/2000/01/rdf-schema#label> ?synonym.\n"
                + "  }\n"
                + "  OPTIONAL {\n"
                + "    {}\n"
                + "    GRAPH <http://linkedlifedata.com/resource/drugbank> {\n"
                + "      OPTIONAL { <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0>\n"
                + "        <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/cellularLocation> ?cellularLocation. }\n"
                + "      OPTIONAL { <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0>\n"
                + "        <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/molecularWeight> ?molecularWeight.}\n"
                + "      OPTIONAL { <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0>\n"
                + "        <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/numberOfResidues> ?numberOfResidues . }\n"
                + "      OPTIONAL { <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0>\n"
                + "        <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/pdbIdPage> ?pdbIdPage . }\n"
                + "      OPTIONAL { <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0>\n"
                + "        <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/specificFunction> ?specificFunction .}  \n"
                + "      OPTIONAL { <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0>\n"
                + "        <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/theoreticalPi> ?theoreticalPi .}\n"
               + "    }"
                + "  }\n"
                + "}\n"
                + "GROUP BY ?target_name ?target_type ?description ?organism ?molecularWeight ?numberOfResidues ?pdbIdPage \n"
                + "         ?specificFunction ?theoreticalPi";
        String replaceQuery = "SELECT DISTINCT ?target_name ?target_type ?description ?organism \n"
                + "(GROUP_CONCAT( DISTINCT ?keyword ; SEPARATOR=\" , \") as ?keywords ) \n"
                + "(GROUP_CONCAT( DISTINCT ?synonym ; SEPARATOR=\" , \" ) as ?synonyms) \n"
                + "(GROUP_CONCAT( DISTINCT ?cellularLocation ; SEPARATOR=\" , \" ) as ?cellularLocations ) \n"
                + "?molecularWeight ?numberOfResidues ?pdbIdPage ?specificFunction ?theoreticalPi\n"
                + "WHERE {\n"
                + "  GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "    <http://www.conceptwiki.org/concept/dba8725c-fda4-493c-b876-3392842e63a0> \n"
                + "      <http://www.w3.org/2004/02/skos/core#prefLabel> ?target_name."
                + "  }\n"
                + "  GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "    ?replacedURI1 <http://rdf.farmbio.uu.se/chembl/onto/#hasKeyword> ?keyword.\n"
                + "    ?replacedURI1 <http://rdf.farmbio.uu.se/chembl/onto/#hasDescription> ?description.\n"
                + "    ?replacedURI1 <http://www.w3.org/2000/01/rdf-schema#subClassOf> ?target_type.\n"
                + "    ?replacedURI1 <http://rdf.farmbio.uu.se/chembl/onto/#organism> ?organism.\n"
                + "    ?replacedURI1 <http://www.w3.org/2000/01/rdf-schema#label> ?synonym.\n"
                + "    FILTER (?replacedURI1 = <http://data.kasabi.com/dataset/chembl-rdf/molecule/m276734> \n"
                + "         || ?replacedURI1 =  <http://data.kasabi.com/dataset/chembl-rdf/target/t197>)"
                + "  }\n"
                + "  OPTIONAL {\n"
                + "    GRAPH <http://linkedlifedata.com/resource/drugbank> {\n"
                + "      OPTIONAL { ?replacedURI2 <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/cellularLocation> ?cellularLocation. }\n"
                + "      OPTIONAL { ?replacedURI2 <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/molecularWeight> ?molecularWeight.}\n"
                + "      OPTIONAL { ?replacedURI2 <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/numberOfResidues> ?numberOfResidues . }\n"
                + "      OPTIONAL { ?replacedURI2 <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/pdbIdPage> ?pdbIdPage . }\n"
                + "      OPTIONAL { ?replacedURI2 <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/specificFunction> ?specificFunction .}  \n"
                + "      OPTIONAL { ?replacedURI2 <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/theoreticalPi> ?theoreticalPi .}\n"
                + "      FILTER (?replacedURI2 = <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugs/DB00398> \n"
                + "           || ?replacedURI2 = <http://www4.wiwiss.fu-berlin.de/drugbank/resource/targets/228>)"
                + "    }"
                + "  }\n"
                + "}\n"
                + "GROUP BY ?target_name ?target_type ?description ?organism ?molecularWeight ?numberOfResidues ?pdbIdPage \n"
                + "         ?specificFunction ?theoreticalPi";
        queries.put(queryCase.key, queryCase);
   }

   private void loadProteinPharmacology_count() {
        QueryCase queryCase = new QueryCase();
        queryCase.key = "OpsProteinPharmacology_count";
        queryCase.name = "Ops Protein Pharmacology Count Query";
        queryCase.originalQuery = "SELECT ( COUNT(DISTINCT ?assay_uri) as ?count) \n"
                + "WHERE {\n"
                + "  GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "    <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> \n"
                + "       <http://rdf.farmbio.uu.se/chembl/onto/#organism> ?assay_organism. \n"
                + "    ?assay_uri <http://rdf.farmbio.uu.se/chembl/onto/#hasTarget> \n"
                + "       <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5>.\n"
                + "    ?activity_uri <http://rdf.farmbio.uu.se/chembl/onto/#onAssay> ?assay_uri ;"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#forMolecule> ?compound_uri ;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#type> ?std_type;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#relation> ?relation;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#standardValue> ?std_value;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#standardUnits> ?std_unit;\n"
                + "  }\n"
                + "}";
        queryCase.replaceQuery = "SELECT ( COUNT(DISTINCT ?assay_uri) as ?count) \n"
                + "WHERE {\n"
                + "  GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "    ?replacedURI1 <http://rdf.farmbio.uu.se/chembl/onto/#organism> ?assay_organism. \n"
                + "    ?assay_uri <http://rdf.farmbio.uu.se/chembl/onto/#hasTarget> ?replacedURI1.\n"
                + "    ?activity_uri <http://rdf.farmbio.uu.se/chembl/onto/#onAssay> ?assay_uri ;"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#forMolecule> ?compound_uri ;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#type> ?std_type;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#relation> ?relation;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#standardValue> ?std_value;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#standardUnits> ?std_unit;\n"
                + "    FILTER (?replacedURI1 = <http://data.kasabi.com/dataset/chembl-rdf/molecule/m276734> \n"
                + "         || ?replacedURI1 =  <http://data.kasabi.com/dataset/chembl-rdf/target/t197>)\n"
                + "  }\n"
                + "}";
        queries.put(queryCase.key, queryCase);
    }

   private void loadCompoundPharmacology_count() {
        QueryCase queryCase = new QueryCase();
        queryCase.key = "OpsCompoundPharmacology_count";
        queryCase.name = "Ops Compound Pharmacology Count Query";
        queryCase.originalQuery = "SELECT ( COUNT ( ?assay_uri ) AS ?count ) \n"
                + "WHERE { \n"
                + "  GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "    ?activity_uri <http://rdf.farmbio.uu.se/chembl/onto/#forMolecule> \n"
                + "         <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5>;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#type> ?std_type;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#relation> ?relation;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#standardValue> ?std_value;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#standardUnits> ?std_unit;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#onAssay> ?assay_uri . \n"
                + "    ?assay_uri <http://rdf.farmbio.uu.se/chembl/onto/#hasTarget> ?target_uri . \n"
                + "    ?target_uri <http://purl.org/dc/elements/1.1/title> ?target_name .\n"
                + "    ?target_uri <http://rdf.farmbio.uu.se/chembl/onto/#organism> ?assay_organism . \n"
                + "  }\n"
                + "}";
        queryCase.replaceQuery = "SELECT ( COUNT ( ?assay_uri ) AS ?count ) \n"
                + "WHERE { \n"
                + "  GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "    ?activity_uri <http://rdf.farmbio.uu.se/chembl/onto/#forMolecule> ?replacedURI1;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#type> ?std_type;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#relation> ?relation;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#standardValue> ?std_value;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#standardUnits> ?std_unit;\n"
                + "                  <http://rdf.farmbio.uu.se/chembl/onto/#onAssay> ?assay_uri . \n"
                + "    ?assay_uri <http://rdf.farmbio.uu.se/chembl/onto/#hasTarget> ?target_uri . \n"
                + "    ?target_uri <http://purl.org/dc/elements/1.1/title> ?target_name .\n"
                + "    ?target_uri <http://rdf.farmbio.uu.se/chembl/onto/#organism> ?assay_organism . \n"
                + "    FILTER (?replacedURI1 = <http://data.kasabi.com/dataset/chembl-rdf/molecule/m276734> \n"
                + "         || ?replacedURI1 =  <http://data.kasabi.com/dataset/chembl-rdf/target/t197>)\n"
                + "  }\n"
                + "}";
        queries.put(queryCase.key, queryCase);
   }

   private void load() {
        QueryCase queryCase = new QueryCase();
        queryCase.key = "Ops";
        queryCase.name = "Ops  Query";
        queryCase.originalQuery = "";
        queries.put(queryCase.key, queryCase);
    }

 }
