/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.ac.man.cs.openphacts.queryexpander.queryLoader;

/**
 *
 * @author Christian
 */
public class OpsReplacementLoader extends QueryCaseLoader{
    
   public OpsReplacementLoader(){
       loadNoMapping();
       loadcompoundPharma_count();
       loadProteinInfo();
       loadCompoundPharmaPages();
       loadCompoundPharma();
       loadInnerLimit();
       loadManyWhere();
 //      loadCurlyBrackBug();
   } 
   
  private void loadNoMapping() {
        QueryCase queryCase = new QueryCase();
        queryCase.key = "OpsReplacementNoMapping";
        queryCase.name = "Query which will provide no mapping";
        queryCase.originalQuery = "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX ops: <http://www.openphacts.org/api#>\n"
                + "CONSTRUCT { 		\n"
                + "  ?kasabiId ops:compoundPharmacologyTotalResults ?count .   \n"
                + "} WHERE {\n"
                + "  {\n "
                + "    SELECT (COUNT(?activity_uri) AS ?count) {\n"
                + "      GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "        ?activity_uri chembl:forMolecule ?kasabiId;\n"
                + "                      chembl:type ?std_type;\n"
                + "                      chembl:relation ?relation;\n"
                + "                      chembl:standardValue ?std_value;\n"
                + "                      chembl:standardUnits ?std_unit;\n"
                + "                      chembl:onAssay ?assay_uri . \n"
                + "      }\n"
                + "    }\n"
                + "  } \n"
                + "}";
        queryCase.replaceQuery = "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX ops: <http://www.openphacts.org/api#>\n"
                + "CONSTRUCT { 		\n"
                + "  ?kasabiId ops:compoundPharmacologyTotalResults ?count .   \n"
                + "} WHERE {\n"
                + "  {\n "
                + "    SELECT (COUNT(?activity_uri) AS ?count) {\n"
                + "      GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "        ?activity_uri chembl:forMolecule ?kasabiId;\n"
                + "                      chembl:type ?std_type;\n"
                + "                      chembl:relation ?relation;\n"
                + "                      chembl:standardValue ?std_value;\n"
                + "                      chembl:standardUnits ?std_unit;\n"
                + "                      chembl:onAssay ?assay_uri . \n"
                + "      FILTER (?kasabiId = \"No Mappings Found\")\n"
                + "      }\n"
                + "    }\n"
                + "  } \n"
                + "}";
        queryCase.addParameter("?kasabiId");
        queryCase.insertURI = "http://www.example.com/notindata";
        queries.put(queryCase.key, queryCase);
    }
   
  private void loadcompoundPharma_count() {
        QueryCase queryCase = new QueryCase();
        queryCase.key = "OpsReplacementCompoundPharma_count";
        queryCase.name = "Compound Pharma Count Query";
        queryCase.originalQuery = "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX ops: <http://www.openphacts.org/api#>\n"
                + "CONSTRUCT { 		\n"
                + "  ?kasabiId ops:compoundPharmacologyTotalResults ?count .   \n"
                + "} WHERE {\n"
                + "  {\n "
                + "    SELECT (COUNT(?activity_uri) AS ?count) {\n"
                + "      GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "        ?activity_uri chembl:forMolecule ?kasabiId;\n"
                + "                      chembl:type ?std_type;\n"
                + "                      chembl:relation ?relation;\n"
                + "                      chembl:standardValue ?std_value;\n"
                + "                      chembl:standardUnits ?std_unit;\n"
                + "                      chembl:onAssay ?assay_uri . \n"
                + "      }\n"
                + "    }\n"
                + "  } \n"
                + "}";
        queryCase.replaceQuery = "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX ops: <http://www.openphacts.org/api#>\n"
                + "CONSTRUCT { 		\n"
                + "  ?kasabiId ops:compoundPharmacologyTotalResults ?count .   \n"
                + "} WHERE {\n"
                + "  {\n "
                + "    SELECT (COUNT(?activity_uri) AS ?count) {\n"
                + "      GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "        ?activity_uri chembl:forMolecule ?kasabiId;\n"
                + "                      chembl:type ?std_type;\n"
                + "                      chembl:relation ?relation;\n"
                + "                      chembl:standardValue ?std_value;\n"
                + "                      chembl:standardUnits ?std_unit;\n"
                + "                      chembl:onAssay ?assay_uri . \n"
                + "      FILTER (?kasabiId = <http://data.kasabi.com/dataset/chembl-rdf/molecule/m276734>)\n"
                + "      }\n"
                + "    }\n"
                + "  } \n"
                + "}";
        queryCase.addParameter("?kasabiId");
        queryCase.insertURI = "http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5";
        queries.put(queryCase.key, queryCase);
    }

  private void loadProteinInfo() {
        QueryCase queryCase = new QueryCase();
        queryCase.key = "OpsReplacementProteinInfo";
        queryCase.name = "Protein Info Query";
        queryCase.originalQuery = "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n"
                + "PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>\n"
                + "CONSTRUCT {\n"
                + " ?concepWikiURI skos:prefLabel ?target_name ;\n"
                + "		skos:exactMatch ?kasabiURI ;\n"
                + "		skos:exactMatch ?drugbankURI .\n"
                + "	?kasabiURI chembl:hasKeyword ?keywords ;\n"
                + "		chembl:hasDescription ?description ;\n"
                + "		rdfs:subClassOf ?target_type ;\n"
                + "		chembl:organism ?organism ;\n"
                + "		rdfs:label ?synonyms .\n"
                + "	?drugbankURI drugbank:cellularLocation ?cellularLocations ;\n"
                + "		drugbank:molecularWeight ?molecularWeight ;\n"
                + "		drugbank:numberOfResidues ?numberOfResidues ;\n"
                + "		drugbank:pdbIdPage ?pdbIdPage ;\n"
                + "		drugbank:specificFunction ?specificFunction ;\n"
                + "		drugbank:theoreticalPi ?theoreticalPi \n"
                + "}\n"
                + "WHERE {\n"
                + " GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "		?concepWikiURI skos:prefLabel ?target_name.\n"
                + "	}\n"
                + "	{ \n"
                + "     SELECT DISTINCT ?kasabiURI ?target_type ?description ?organism \n "
                + "         (GROUP_CONCAT( DISTINCT ?keyword ; SEPARATOR=\" , \") as ?keywords ) \n"
                + "         (GROUP_CONCAT( DISTINCT ?synonym ; SEPARATOR=\" , \" ) as ?synonyms) {\n"
                + "		GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "			?kasabiURI chembl:hasKeyword ?keyword ;\n"
                + "				chembl:hasDescription ?description ;\n"
                + "				rdfs:subClassOf ?target_type ;\n"
                + "				chembl:organism ?organism ;\n"
                + "				rdfs:label ?synonym .\n"
                + "		}\n"
                + "	} GROUP BY ?target_type ?description ?organism ?kasabiURI}\n"
                + "	{ \n"
                + "     SELECT DISTINCT ?drugbankURI ?molecularWeight ?numberOfResidues ?pdbIdPage ?specificFunction ?theoreticalPi \n"
                + "         (GROUP_CONCAT( DISTINCT ?cellularLocation ; SEPARATOR=\" , \" ) as ?cellularLocations ) {"
                + "		GRAPH <http://linkedlifedata.com/resource/drugbank> {\n"
                + "			OPTIONAL { ?drugbankURI drugbank:cellularLocation ?cellularLocation }\n"
                + "			OPTIONAL { ?drugbankURI drugbank:molecularWeight ?molecularWeight }\n"
                + "			OPTIONAL { ?drugbankURI drugbank:numberOfResidues ?numberOfResidues }\n"
                + "			OPTIONAL { ?drugbankURI drugbank:pdbIdPage ?pdbIdPage }\n"
                + "			OPTIONAL { ?drugbankURI drugbank:specificFunction ?specificFunction }\n"
                + "			OPTIONAL { ?drugbankURI drugbank:theoreticalPi ?theoreticalPi }\n"
                + "		}\n"
                + "	} GROUP BY ?molecularWeight ?numberOfResidues ?pdbIdPage ?specificFunction ?theoreticalPi ?drugbankURI }\n"
                + "}";
        queryCase.replaceQuery = "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n"
                + "PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>\n"
                + "CONSTRUCT {\n"
                + " ?concepWikiURI skos:prefLabel ?target_name ;\n"
                + "		skos:exactMatch ?kasabiURI ;\n"
                + "		skos:exactMatch ?drugbankURI .\n"
                + "	?kasabiURI chembl:hasKeyword ?keywords ;\n"
                + "		chembl:hasDescription ?description ;\n"
                + "		rdfs:subClassOf ?target_type ;\n"
                + "		chembl:organism ?organism ;\n"
                + "		rdfs:label ?synonyms .\n"
                + "	?drugbankURI drugbank:cellularLocation ?cellularLocations ;\n"
                + "		drugbank:molecularWeight ?molecularWeight ;\n"
                + "		drugbank:numberOfResidues ?numberOfResidues ;\n"
                + "		drugbank:pdbIdPage ?pdbIdPage ;\n"
                + "		drugbank:specificFunction ?specificFunction ;\n"
                + "		drugbank:theoreticalPi ?theoreticalPi \n"
                + "}\n"
                + "WHERE {\n"
                + " GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "		?concepWikiURI skos:prefLabel ?target_name.\n"
                + "     FILTER (?concepWikiURI = <http://www.conceptwiki.org/concept/516c9a26-885c-4920-9a13-d0a68cf99084>)\n"
                + "	}\n"
                + "	{ \n"
                + "     SELECT DISTINCT ?kasabiURI ?target_type ?description ?organism "
                + "         (GROUP_CONCAT( DISTINCT ?keyword ; SEPARATOR=\" , \") as ?keywords ) "
                + "         (GROUP_CONCAT( DISTINCT ?synonym ; SEPARATOR=\" , \" ) as ?synonyms) {\n"
                + "		GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "			?kasabiURI chembl:hasKeyword ?keyword ;\n"
                + "				chembl:hasDescription ?description ;\n"
                + "				rdfs:subClassOf ?target_type ;\n"
                + "				chembl:organism ?organism ;\n"
                + "				rdfs:label ?synonym .\n"
                + "         FILTER (?kasabiURI = <http://data.kasabi.com/dataset/chembl-rdf/target/t11063>)\n"
                + "		}\n"
                + "	} GROUP BY ?target_type ?description ?organism ?kasabiURI}\n"
                + "	{ \n"
                + "     SELECT DISTINCT ?drugbankURI ?molecularWeight ?numberOfResidues ?pdbIdPage ?specificFunction ?theoreticalPi \n"
                + "         (GROUP_CONCAT( DISTINCT ?cellularLocation ; SEPARATOR=\" , \" ) as ?cellularLocations ) {"
                + "		GRAPH <http://linkedlifedata.com/resource/drugbank> {\n"
                + "			OPTIONAL { ?drugbankURI drugbank:cellularLocation ?cellularLocation }\n"
                + "			OPTIONAL { ?drugbankURI drugbank:molecularWeight ?molecularWeight }\n"
                + "			OPTIONAL { ?drugbankURI drugbank:numberOfResidues ?numberOfResidues }\n"
                + "			OPTIONAL { ?drugbankURI drugbank:pdbIdPage ?pdbIdPage }\n"
                + "			OPTIONAL { ?drugbankURI drugbank:specificFunction ?specificFunction }\n"
                + "			OPTIONAL { ?drugbankURI drugbank:theoreticalPi ?theoreticalPi }\n"
                + "         FILTER (?drugbankURI =<http://www4.wiwiss.fu-berlin.de/drugbank/resource/targets/6131>)\n"
                + "		}\n"
                + "	} GROUP BY ?molecularWeight ?numberOfResidues ?pdbIdPage ?specificFunction ?theoreticalPi ?drugbankURI }\n"
                + "}";
        queryCase.addParameter("?concepWikiURI");
        queryCase.addParameter("?kasabiURI");
        queryCase.addParameter("?drugbankURI");
        queryCase.insertURI = "http://www.conceptwiki.org/concept/516c9a26-885c-4920-9a13-d0a68cf99084";
        queries.put(queryCase.key, queryCase);
    }

    private void loadCompoundPharmaPages() {
        QueryCase queryCase = new QueryCase();
        queryCase.key = "OpsReplacementCompoundPharmaPages";
        queryCase.name = "Compound Pharma Pages Query";
        queryCase.originalQuery = "PREFIX void: <http://rdfs.org/ns/void#>\n"
                + "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX chemspider: <http://rdf.chemspider.com/#>\n"
                + "PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>\n"
                + "PREFIX dc: <http://purl.org/dc/elements/1.1/>\n"
                + "PREFIX ops: <http://www.openphacts.org/api#>\n"
                + "PREFIX sio: <http://semanticscience.org/resource/>\n"
                + "PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>\n"
                + "CONSTRUCT {\n" 
                + "		?item chembl:forMolecule ?kasabiURI;\n"
                + "			chembl:type ?std_type;\n"
                + "			chembl:relation ?relation;\n"
                + "			chembl:standardValue ?std_value;\n"
                + "			chembl:standardUnits ?std_unit;\n"
                + "			chembl:onAssay ?assay_uri ;\n"
                + "			void:inDataset <http://data.kasabi.com/dataset/chembl-rdf> .\n"
                + "		?assay_uri chembl:hasTarget [\n"
                + "				ops:concatenatedURIs ?target_uris ;\n"
                + "				dc:title ?target_names ;\n"
                + "				chembl:organism ?target_organisms ];\n"
                + "			void:inDataset <http://data.kasabi.com/dataset/chembl-rdf> .\n"
                + "		?kasabiURI skos:exactMatch ?concepWikiURI .\n"
                + "		?concepWikiURI skos:prefLabel ?compound_name ;\n"
                + "			void:inDataset <http://www.conceptwiki.org/> .\n"
                + "		?kasabiURI skos:exactMatch ?chemspiderURI .\n"
                + "		?chemspiderURI chemspider:smiles ?smiles ;\n"
                + "			chemspider:inchi ?inchi ;\n"
                + "			chemspider:inchikey ?inchiKey;\n"
                + "			void:inDataset <http://rdf.chemspider.com/> .\n"
                + "		?kasabiURI ?bNode1 ?molweight ;\n"
                + "			?bNode2 ?num_ro5_violations ;\n"
                + "			void:inDataset <http://data.kasabi.com/dataset/chembl-rdf> .\n"
                + "		?kasabiURI skos:exactMatch ?drugbankURI .\n"
                + "		?drugbankURI drugbank:drugType ?drugTypes ;\n"
                + "			drugbank:genericName ?drug_name ;\n"
                + "			void:inDataset <http://linkedlifedata.com/resource/drugbank>  \n"
                + "} \n"
                + "WHERE {\n"
                + "	{\n"
                + "		GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "			?concepWikiURI skos:prefLabel ?compound_name.\n"
                + "		}\n"
                + "		GRAPH <http://www.chemspider.com> {\n"
                + "			?chemspiderURI chemspider:smiles ?smiles ;\n"
                + "				chemspider:inchi ?inchi ;\n"
                + "				chemspider:inchikey ?inchiKey.\n"
                + "		}\n"
                + "		{\n"
                + "			SELECT DISTINCT ?drugbankURI ?drug_name \n"
                + "             (GROUP_CONCAT(DISTINCT ?drugType ; SEPARATOR=' , ') AS ?drugTypes) {\n"
                + "				GRAPH <http://linkedlifedata.com/resource/drugbank> {\n"
                + "					?drugbankURI drugbank:genericName ?drug_name ;\n"
                + "						drugbank:drugType ?drugType_uri .\n"
                + "					?drugType_uri rdfs:label ?drugType.\n"
                + "				}\n"
                + "			} GROUP BY ?drug_name ?drugbankURI\n"
                + "		}\n"
                + "	}\n"
                + "	{\n"       
                + "		SELECT DISTINCT ?item ?std_type ?relation ?std_value ?std_unit ?assay_uri \n"
                + "         ?bNode1 ?molweight ?bNode2 ?num_ro5_violations \n"
                + "         (GROUP_CONCAT(DISTINCT ?target_uri ; SEPARATOR=' , ') AS ?target_uris) \n"
                + "         (GROUP_CONCAT(DISTINCT ?target_name ; SEPARATOR=' , ') AS ?target_names) \n"
                + "         (GROUP_CONCAT(DISTINCT ?target_organism ; SEPARATOR=' , ') AS ?target_organisms) \n"
                + "     {\n"
                + "			GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "				?item chembl:forMolecule ?kasabiURI ;\n"
                + "					chembl:type ?std_type;\n"
                + "					chembl:relation ?relation;\n"
                + "					chembl:standardValue ?std_value;\n"
                + "					chembl:standardUnits ?std_unit;\n"
                + "					chembl:onAssay ?assay_uri .\n"
                + "				?assay_uri chembl:hasTarget ?target_uri .\n"
                + "				?target_uri dc:title ?target_name ;\n"
                + "					chembl:organism ?target_organism .\n"
                + "				OPTIONAL { ?kasabiURI sio:CHEMINF_000200 ?bNode1 .\n"
                + "					?bNode1 a sio:CHEMINF_000198 ;\n"
                + "						sio:SIO_000300 ?molweight. }\n"
                + "				OPTIONAL { ?kasabiURI sio:CHEMINF_000200 ?bNode2 .\n"
                + "					?bNode2 a sio:CHEMINF_000314 ;\n"
                + "						sio:SIO_000300 ?num_ro5_violations. }\n"
                + "			}\n"
                + "		} GROUP BY ?item ?std_type ?relation ?std_value ?std_unit ?assay_uri ?bNode1 ?molweight ?bNode2 ?num_ro5_violations  \n"
                + "	} \n"
                + "} LIMIT 5  OFFSET 0";
        queryCase.replaceQuery = "PREFIX void: <http://rdfs.org/ns/void#>\n"
                + "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX chemspider: <http://rdf.chemspider.com/#>\n"
                + "PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>\n"
                + "PREFIX dc: <http://purl.org/dc/elements/1.1/>\n"
                + "PREFIX ops: <http://www.openphacts.org/api#>\n"
                + "PREFIX sio: <http://semanticscience.org/resource/>\n"
                + "PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>\n"
                + "CONSTRUCT {\n" 
                + "		?item chembl:forMolecule ?kasabiURI;\n"
                + "			chembl:type ?std_type;\n"
                + "			chembl:relation ?relation;\n"
                + "			chembl:standardValue ?std_value;\n"
                + "			chembl:standardUnits ?std_unit;\n"
                + "			chembl:onAssay ?assay_uri ;\n"
                + "			void:inDataset <http://data.kasabi.com/dataset/chembl-rdf> .\n"
                + "		?assay_uri chembl:hasTarget [\n"
                + "				ops:concatenatedURIs ?target_uris ;\n"
                + "				dc:title ?target_names ;\n"
                + "				chembl:organism ?target_organisms ];\n"
                + "			void:inDataset <http://data.kasabi.com/dataset/chembl-rdf> .\n"
                + "		?kasabiURI skos:exactMatch ?concepWikiURI .\n"
                + "		?concepWikiURI skos:prefLabel ?compound_name ;\n"
                + "			void:inDataset <http://www.conceptwiki.org/> .\n"
                + "		?kasabiURI skos:exactMatch ?chemspiderURI .\n"
                + "		?chemspiderURI chemspider:smiles ?smiles ;\n"
                + "			chemspider:inchi ?inchi ;\n"
                + "			chemspider:inchikey ?inchiKey;\n"
                + "			void:inDataset <http://rdf.chemspider.com/> .\n"
                + "		?kasabiURI ?bNode1 ?molweight ;\n"
                + "			?bNode2 ?num_ro5_violations ;\n"
                + "			void:inDataset <http://data.kasabi.com/dataset/chembl-rdf> .\n"
                + "		?kasabiURI skos:exactMatch ?drugbankURI .\n"
                + "		?drugbankURI drugbank:drugType ?drugTypes ;\n"
                + "			drugbank:genericName ?drug_name ;\n"
                + "			void:inDataset <http://linkedlifedata.com/resource/drugbank>  \n"
                + "} \n"
                + "WHERE {\n"
                + "	{\n"
                + "		GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "			?concepWikiURI skos:prefLabel ?compound_name.\n"
                + "     FILTER (?concepWikiURI = <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5>)\n"
                + "		}\n"
                + "		GRAPH <http://www.chemspider.com> {\n"
                + "			?chemspiderURI chemspider:smiles ?smiles ;\n"
                + "				chemspider:inchi ?inchi ;\n"
                + "				chemspider:inchikey ?inchiKey.\n"
                + "         FILTER (?chemspiderURI = <http://rdf.chemspider.com/187440>)\n"
                + "		}\n"
                + "		{\n"
                + "			SELECT DISTINCT ?drugbankURI ?drug_name \n"
                + "             (GROUP_CONCAT(DISTINCT ?drugType ; SEPARATOR=' , ') AS ?drugTypes) {\n"
                + "				GRAPH <http://linkedlifedata.com/resource/drugbank> {\n"
                + "					?drugbankURI drugbank:genericName ?drug_name ;\n"
                + "						drugbank:drugType ?drugType_uri .\n"
                + "					?drugType_uri rdfs:label ?drugType.\n"
                + "                 FILTER (?drugbankURI = <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugs/DB00398>)\n"
                + "				}\n"
                + "			} GROUP BY ?drug_name ?drugbankURI\n"
                + "		}\n"
                + "	}\n"
                + "	{\n"       
                + "		SELECT DISTINCT ?item ?std_type ?relation ?std_value ?std_unit ?assay_uri \n"
                + "         ?bNode1 ?molweight ?bNode2 ?num_ro5_violations \n"
                + "         (GROUP_CONCAT(DISTINCT ?target_uri ; SEPARATOR=' , ') AS ?target_uris) \n"
                + "         (GROUP_CONCAT(DISTINCT ?target_name ; SEPARATOR=' , ') AS ?target_names) \n"
                + "         (GROUP_CONCAT(DISTINCT ?target_organism ; SEPARATOR=' , ') AS ?target_organisms) \n"
                + "     {\n"
                + "			GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "				?item chembl:forMolecule ?kasabiURI ;\n"
                + "					chembl:type ?std_type;\n"
                + "					chembl:relation ?relation;\n"
                + "					chembl:standardValue ?std_value;\n"
                + "					chembl:standardUnits ?std_unit;\n"
                + "					chembl:onAssay ?assay_uri .\n"
                + "				?assay_uri chembl:hasTarget ?target_uri .\n"
                + "				?target_uri dc:title ?target_name ;\n"
                + "					chembl:organism ?target_organism .\n"
                + "				OPTIONAL { ?kasabiURI sio:CHEMINF_000200 ?bNode1 .\n"
                + "					?bNode1 a sio:CHEMINF_000198 ;\n"
                + "						sio:SIO_000300 ?molweight. }\n"
                + "				OPTIONAL { ?kasabiURI sio:CHEMINF_000200 ?bNode2 .\n"
                + "					?bNode2 a sio:CHEMINF_000314 ;\n"
                + "						sio:SIO_000300 ?num_ro5_violations. }\n"
                + "             FILTER (?kasabiURI = <http://data.kasabi.com/dataset/chembl-rdf/molecule/m276734> )\n"
                + "			}\n"
                + "		} GROUP BY ?item ?std_type ?relation ?std_value ?std_unit ?assay_uri ?bNode1 ?molweight ?bNode2 ?num_ro5_violations  \n"
                + "	} \n"
                + "} LIMIT 5  OFFSET 0";
        queryCase.addParameter("?concepWikiURI");
        queryCase.addParameter("?chemspiderURI");
        queryCase.addParameter("?kasabiURI");
        queryCase.addParameter("?drugbankURI");
        queryCase.insertURI = "http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5";
        queries.put(queryCase.key, queryCase);
    }

    private void loadCompoundPharma() {
        QueryCase queryCase = new QueryCase();
        queryCase.key = "OpsReplacementCompoundPharma";
        queryCase.name = "Compound Pharma Query";
        queryCase.originalQuery = ""
                + "PREFIX void: <http://rdfs.org/ns/void#>\n"
                + "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX chemspider: <http://rdf.chemspider.com/#>\n"
                + "PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>\n"
                + "PREFIX dc: <http://purl.org/dc/elements/1.1/>\n"
                + "PREFIX ops: <http://www.openphacts.org/api#>\n"
                + "PREFIX sio: <http://semanticscience.org/resource/>\n"
                + "PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>\n"
                + "PREFIX owl:<http://www.w3.org/2002/07/owl#>\n"
                + "CONSTRUCT { \n"
                + "	?concepWikiURI skos:prefLabel ?compound_name ;\n"
                + "		skos:exactMatch ?chemspiderURI .\n"
                + "	?chemspiderURI chemspider:smiles ?smiles ;\n"
                + "		chemspider:inchi ?inchi ; \n"
                + "		chemspider:inchikey ?inchi_key ;\n"
                + "		void:inDataset <http://www.chemspider.com> .\n"
                + "	?concepWikiURI skos:exactMatch ?drugbankURI .\n"
                + "	?drugbankURI drugbank:genericName ?drug_name ;\n"
                + "		drugbank:drugType ?drugType ;\n"
                + "		void:inDataset <http://linkedlifedata.com/resource/drugbank>.\n"
                + "	?concepWikiURI skos:exactMatch ?kasabiURI . \n"
                + "	?kasabiURI ?node1 ?molweight ;\n"
                + "		?node2 ?num_ro5_violations ;\n"
                + "		ops:hasActivity ?activity_uri ;\n"
                + "		void:inDataset <http://data.kasabi.com/dataset/chembl-rdf> .\n"
                + "	ops:hasActivity owl:inverseOf chembl:forMolecule .\n"
                + "	?activity_uri chembl:forMolecule ?kasabiURI;\n"
                + "		chembl:type ?std_type;\n"
                + "		chembl:relation ?relation;\n"
                + "		chembl:standardValue ?std_value;\n"
                + "		chembl:standardUnits ?std_unit;\n"
                + "		chembl:onAssay ?assay_uri .\n"
                + "	?assay_uri chembl:hasTarget ?target_uri .\n"
                + "	?target_uri dc:title ?target_name ;\n"
                + "		chembl:organism ?target_organism .\n"
                + "} WHERE { \n"
                + "	GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "		?concepWikiURI skos:prefLabel ?compound_name.\n"
                + "	}\n"
                + "	GRAPH <http://www.chemspider.com> {\n"
                + "		?chemspiderURI chemspider:smiles ?smiles ;\n"
                + "			chemspider:inchi ?inchi ;\n"
                + "			chemspider:inchikey ?inchi_key.\n"
                 + "	}\n"
                + "	GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "		?activity_uri chembl:forMolecule ?kasabiURI;\n"
                + "			chembl:type ?std_type;\n"
                + "			chembl:relation ?relation\n;"
                + "			chembl:standardValue ?std_value;\n"
                + "			chembl:standardUnits ?std_unit;\n"
                + "			chembl:onAssay ?assay_uri . \n"
                + "		?assay_uri chembl:hasTarget ?target_uri . \n"
                + "		?target_uri dc:title ?target_name ;\n"
                + "			chembl:organism ?target_organism .\n"
                + "		OPTIONAL { ?kasabiURI sio:CHEMINF_000200 ?node1 .\n"
                + "			?node1 a sio:CHEMINF_000198 ;\n"
                + "				sio:SIO_000300 ?molweight. }\n"
                + "		OPTIONAL { ?kasabiURI sio:CHEMINF_000200 ?node2 .\n"
                + "			?node2 a sio:CHEMINF_000314 ;\n"
                + "				sio:SIO_000300 ?num_ro5_violations.}\n"
                + "	}\n"
                + "	GRAPH <http://linkedlifedata.com/resource/drugbank> {\n"
                + "		?drugbankURI drugbank:genericName ?drug_name ;\n"
                + "			drugbank:drugType ?drugType_uri .\n"
                + "		?drugType_uri rdfs:label ?drugType. \n"
                + "	} \n"
                + "}";
        queryCase.replaceQuery = ""
                + "PREFIX void: <http://rdfs.org/ns/void#>\n"
                + "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX chemspider: <http://rdf.chemspider.com/#>\n"
                + "PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>\n"
                + "PREFIX dc: <http://purl.org/dc/elements/1.1/>\n"
                + "PREFIX ops: <http://www.openphacts.org/api#>\n"
                + "PREFIX sio: <http://semanticscience.org/resource/>\n"
                + "PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>\n"
                + "PREFIX owl:<http://www.w3.org/2002/07/owl#>\n"
                + "CONSTRUCT { \n"
                + "	?concepWikiURI skos:prefLabel ?compound_name ;\n"
                + "		skos:exactMatch ?chemspiderURI .\n"
                + "	?chemspiderURI chemspider:smiles ?smiles ;\n"
                + "		chemspider:inchi ?inchi ; \n"
                + "		chemspider:inchikey ?inchi_key ;\n"
                + "		void:inDataset <http://www.chemspider.com> .\n"
                + "	?concepWikiURI skos:exactMatch ?drugbankURI .\n"
                + "	?drugbankURI drugbank:genericName ?drug_name ;\n"
                + "		drugbank:drugType ?drugType ;\n"
                + "		void:inDataset <http://linkedlifedata.com/resource/drugbank>.\n"
                + "	?concepWikiURI skos:exactMatch ?kasabiURI . \n"
                + "	?kasabiURI ?node1 ?molweight ;\n"
                + "		?node2 ?num_ro5_violations ;\n"
                + "		ops:hasActivity ?activity_uri ;\n"
                + "		void:inDataset <http://data.kasabi.com/dataset/chembl-rdf> .\n"
                + "	ops:hasActivity owl:inverseOf chembl:forMolecule .\n"
                + "	?activity_uri chembl:forMolecule ?kasabiURI;\n"
                + "		chembl:type ?std_type;\n"
                + "		chembl:relation ?relation;\n"
                + "		chembl:standardValue ?std_value;\n"
                + "		chembl:standardUnits ?std_unit;\n"
                + "		chembl:onAssay ?assay_uri .\n"
                + "	?assay_uri chembl:hasTarget ?target_uri .\n"
                + "	?target_uri dc:title ?target_name ;\n"
                + "		chembl:organism ?target_organism .\n"
                + "} WHERE { \n"
                + "	GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "		?concepWikiURI skos:prefLabel ?compound_name.\n"
                + "     FILTER (?concepWikiURI = <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5>)\n"
                + "	}\n"
                + "	GRAPH <http://www.chemspider.com> {\n"
                + "		?chemspiderURI chemspider:smiles ?smiles ;\n"
                + "			chemspider:inchi ?inchi ;\n"
                + "			chemspider:inchikey ?inchi_key.\n"
                + "         FILTER (?chemspiderURI = <http://rdf.chemspider.com/187440>)\n"
                + "	}\n"
                + "	GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "		?activity_uri chembl:forMolecule ?kasabiURI;\n"
                + "			chembl:type ?std_type;\n"
                + "			chembl:relation ?relation\n;"
                + "			chembl:standardValue ?std_value;\n"
                + "			chembl:standardUnits ?std_unit;\n"
                + "			chembl:onAssay ?assay_uri . \n"
                + "		?assay_uri chembl:hasTarget ?target_uri . \n"
                + "		?target_uri dc:title ?target_name ;\n"
                + "			chembl:organism ?target_organism .\n"
                + "		OPTIONAL { ?kasabiURI sio:CHEMINF_000200 ?node1 .\n"
                + "			?node1 a sio:CHEMINF_000198 ;\n"
                + "				sio:SIO_000300 ?molweight. }\n"
                + "		OPTIONAL { ?kasabiURI sio:CHEMINF_000200 ?node2 .\n"
                + "			?node2 a sio:CHEMINF_000314 ;\n"
                + "				sio:SIO_000300 ?num_ro5_violations.}\n"
                + "     FILTER (?kasabiURI = <http://data.kasabi.com/dataset/chembl-rdf/molecule/m276734>)\n"
                + "	}\n"
                + "	GRAPH <http://linkedlifedata.com/resource/drugbank> {\n"
                + "		?drugbankURI drugbank:genericName ?drug_name ;\n"
                + "			drugbank:drugType ?drugType_uri .\n"
                + "		?drugType_uri rdfs:label ?drugType. \n"
                + "     FILTER (?drugbankURI = <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugs/DB00398>)\n"
                + "	} \n"
                + "}";
        queryCase.addParameter("?concepWikiURI");
        queryCase.addParameter("?chemspiderURI");
        queryCase.addParameter("?kasabiURI");
        queryCase.addParameter("?drugbankURI");
        queryCase.insertURI = "http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5";
        queries.put(queryCase.key, queryCase);
    }

   private void loadInnerLimit() {
        QueryCase queryCase = new QueryCase();
        queryCase.key = "OpsReplacement_Inner_Limit";
        queryCase.name = "Query With Inner Limit";
        queryCase.originalQuery = "PREFIX ops: <http://www.openphacts.org/api#>\n"
                + "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX chembl-ops: <http://www.openphacts.org/chembl/onto/#>\n"
                + "PREFIX void: <http://rdfs.org/ns/void#>\n"
                + "PREFIX dc: <http://purl.org/dc/elements/1.1/>\n"
                + "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX chemspider: <http://rdf.chemspider.com/#>\n"
                + "PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>\n"
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n"
                + "PREFIX sio: <http://semanticscience.org/resource/>\n"
                + "CONSTRUCT { \n"
                + "     [] ops:input <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> .\n"
                + "     ?item chembl:forMolecule ?chembl_uri;\n"
                + "         chembl:type ?std_type;\n"
                + "         chembl:relation ?relation;\n"
                + "         chembl:standardValue ?std_value;\n"
                + "         chembl:standardUnits ?std_unit;\n"
                + "         chembl:onAssay ?assay_uri ;\n"
                + "         chembl-ops:normalisedValue ?activity_value ;\n"
                + "         void:inDataset <http://data.kasabi.com/dataset/chembl-rdf> .\n"
                + "     ?assay_uri chembl:hasTarget \n"
                + "         [\n"
                + "             ops:concatenatedURIs ?target_uris ;\n"
                + "             dc:title ?target_names ;\n"
                + "             chembl:organism ?target_organisms \n"
                + "         ];\n"
                + "         void:inDataset <http://data.kasabi.com/dataset/chembl-rdf> .\n"
                + "     ?chembl_uri skos:exactMatch ?cw_uri .\n"
                + "     ?cw_uri skos:prefLabel ?compound_name ;\n"
                + "         void:inDataset <http://www.conceptwiki.org/> .\n"
                + "     ?chembl_uri skos:exactMatch ?cs_uri .\n"
                + "     ?cs_uri chemspider:smiles ?smiles ;\n"
                + "         chemspider:inchi ?inchi ;\n"
                + "         chemspider:inchikey ?inchiKey;\n"
                + "         void:inDataset <http://rdf.chemspider.com/> .\n"
                + "     ?chembl_uri ?bNode1 ?molweight ;\n"
                + "         ?bNode2 ?num_ro5_violations ;\n"
                + "         void:inDataset <http://data.kasabi.com/dataset/chembl-rdf> .\n"
                + "     ?chembl_uri skos:exactMatch ?db_uri .\n"
                + "     ?db_uri drugbank:drugType ?drugTypes ;\n"
                + "         drugbank:genericName ?drug_name ;\n"
                + "         void:inDataset <http://linkedlifedata.com/resource/drugbank>   \n"
                + "}  \n"
                + "WHERE { \n"
                + "     GRAPH <http://www.conceptwiki.org> {\n"
                + "         ?cw_uri skos:prefLabel ?compound_name.\n"
                + "     }\n"
                + "     GRAPH <http://www.chemspider.com> {\n"
                + "         ?cs_uri chemspider:smiles ?smiles ;\n"
                + "             chemspider:inchi ?inchi ;\n"
                + "             chemspider:inchikey ?inchiKey.\n"
                + "     }\n"
                + "     {\n"
                + "         SELECT DISTINCT ?db_uri ?drug_name (GROUP_CONCAT(DISTINCT ?drugType ; SEPARATOR=' , ') AS ?drugTypes) {\n"
                + "             GRAPH <http://linkedlifedata.com/resource/drugbank> {\n"
                + "                 ?db_uri drugbank:genericName ?drug_name ;\n"
                + "                     drugbank:drugType ?drugType_uri .\n"
                + "                 ?drugType_uri rdfs:label ?drugType.\n"
                + "             }\n"
                + "          } GROUP BY ?drug_name ?db_uri\n"
                + "     }\n"
                + "     {       \n"
                + "         SELECT DISTINCT ?item ?chembl_uri ?std_type ?relation ?std_value ?std_unit ?assay_uri \n"
                + "                 ?bNode1 ?molweight ?bNode2 ?num_ro5_violations ?activity_value\n"
                + "                 (GROUP_CONCAT(DISTINCT ?target_uri ; SEPARATOR=' , ') AS ?target_uris) \n"
                + "                 (GROUP_CONCAT(DISTINCT ?target_name ; SEPARATOR=' , ') AS ?target_names) \n"
                + "                 (GROUP_CONCAT(DISTINCT ?target_organism ; SEPARATOR=' , ') AS ?target_organisms) \n"
                + "         { \n"
                + "              GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "                 ?item chembl:forMolecule ?chembl_uri ;\n"
                + "                     chembl:type ?std_type;\n"
                + "                     chembl:relation ?relation;\n"
                + "                     chembl:standardValue ?std_value;\n"
                + "                     chembl:standardUnits ?std_unit;\n"
                + "                     chembl:onAssay ?assay_uri .\n"
                + "                 ?assay_uri chembl:hasTarget ?target_uri .\n"
                + "                 ?target_uri dc:title ?target_name ;\n"
                + "                     chembl:organism ?target_organism .\n"
                + "                 OPTIONAL { "
                + "                     ?chembl_uri sio:CHEMINF_000200 ?bNode1 .\n"
                + "                     ?bNode1 a sio:CHEMINF_000198 ;\n"
                + "                         sio:SIO_000300 ?molweight. \n"
                + "                 }\n"
                + "                 OPTIONAL { "
                + "                     ?chembl_uri sio:CHEMINF_000200 ?bNode2 .\n"
                + "                     ?bNode2 a sio:CHEMINF_000314 ;\n"
                + "                         sio:SIO_000300 ?num_ro5_violations. \n"
                + "                 }\n"
                + "             }\n"
                + "         }\n"
                + "         GROUP BY ?chembl_uri ?item ?std_type ?relation ?std_value ?std_unit ?assay_uri ?bNode1 \n"
                + "                 ?molweight ?bNode2 ?num_ro5_violations ?activity_value  \n"
                + "         ORDER BY ?item   \n"
                + "         LIMIT 10  OFFSET 0 "
                + "     }\n"
                + " }\n";
        queryCase.replaceQuery = "PREFIX ops: <http://www.openphacts.org/api#>\n"
                + "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX chembl-ops: <http://www.openphacts.org/chembl/onto/#>\n"
                + "PREFIX void: <http://rdfs.org/ns/void#>\n"
                + "PREFIX dc: <http://purl.org/dc/elements/1.1/>\n"
                + "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX chemspider: <http://rdf.chemspider.com/#>\n"
                + "PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>\n"
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n"
                + "PREFIX sio: <http://semanticscience.org/resource/>\n"
                + "CONSTRUCT { \n"
                + "     [] ops:input <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5> .\n"
                + "     ?item chembl:forMolecule ?chembl_uri;\n"
                + "         chembl:type ?std_type;\n"
                + "         chembl:relation ?relation;\n"
                + "         chembl:standardValue ?std_value;\n"
                + "         chembl:standardUnits ?std_unit;\n"
                + "         chembl:onAssay ?assay_uri ;\n"
                + "         chembl-ops:normalisedValue ?activity_value ;\n"
                + "         void:inDataset <http://data.kasabi.com/dataset/chembl-rdf> .\n"
                + "     ?assay_uri chembl:hasTarget \n"
                + "         [\n"
                + "             ops:concatenatedURIs ?target_uris ;\n"
                + "             dc:title ?target_names ;\n"
                + "             chembl:organism ?target_organisms \n"
                + "         ];\n"
                + "         void:inDataset <http://data.kasabi.com/dataset/chembl-rdf> .\n"
                + "     ?chembl_uri skos:exactMatch ?cw_uri .\n"
                + "     ?cw_uri skos:prefLabel ?compound_name ;\n"
                + "         void:inDataset <http://www.conceptwiki.org/> .\n"
                + "     ?chembl_uri skos:exactMatch ?cs_uri .\n"
                + "     ?cs_uri chemspider:smiles ?smiles ;\n"
                + "         chemspider:inchi ?inchi ;\n"
                + "         chemspider:inchikey ?inchiKey;\n"
                + "         void:inDataset <http://rdf.chemspider.com/> .\n"
                + "     ?chembl_uri ?bNode1 ?molweight ;\n"
                + "         ?bNode2 ?num_ro5_violations ;\n"
                + "         void:inDataset <http://data.kasabi.com/dataset/chembl-rdf> .\n"
                + "     ?chembl_uri skos:exactMatch ?db_uri .\n"
                + "     ?db_uri drugbank:drugType ?drugTypes ;\n"
                + "         drugbank:genericName ?drug_name ;\n"
                + "         void:inDataset <http://linkedlifedata.com/resource/drugbank>   \n"
                + "}  \n"
                + "WHERE { \n"
                + "     GRAPH <http://www.conceptwiki.org> {\n"
                + "         ?cw_uri skos:prefLabel ?compound_name.\n"
                + "     FILTER (?cw_uri = <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5>)\n"
                + "     }\n"
                + "     GRAPH <http://www.chemspider.com> {\n"
                + "         ?cs_uri chemspider:smiles ?smiles ;\n"
                + "             chemspider:inchi ?inchi ;\n"
                + "             chemspider:inchikey ?inchiKey.\n"
                + "         FILTER (?cs_uri = <http://rdf.chemspider.com/187440>)\n"
                + "     }\n"
                + "     {\n"
                + "         SELECT DISTINCT ?db_uri ?drug_name (GROUP_CONCAT(DISTINCT ?drugType ; SEPARATOR=' , ') AS ?drugTypes) {\n"
                + "             GRAPH <http://linkedlifedata.com/resource/drugbank> {\n"
                + "                 ?db_uri drugbank:genericName ?drug_name ;\n"
                + "                     drugbank:drugType ?drugType_uri .\n"
                + "                 ?drugType_uri rdfs:label ?drugType.\n"
                + "                 FILTER (?db_uri = <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugs/DB00398> )\n"
                + "             }\n"
                + "          } GROUP BY ?drug_name ?db_uri\n"
                + "     }\n"
                + "     {       \n"
                + "         SELECT DISTINCT ?item ?chembl_uri ?std_type ?relation ?std_value ?std_unit ?assay_uri \n"
                + "                 ?bNode1 ?molweight ?bNode2 ?num_ro5_violations ?activity_value\n"
                + "                 (GROUP_CONCAT(DISTINCT ?target_uri ; SEPARATOR=' , ') AS ?target_uris) \n"
                + "                 (GROUP_CONCAT(DISTINCT ?target_name ; SEPARATOR=' , ') AS ?target_names) \n"
                + "                 (GROUP_CONCAT(DISTINCT ?target_organism ; SEPARATOR=' , ') AS ?target_organisms) \n"
                + "         { \n"
                + "              GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "                 ?item chembl:forMolecule ?chembl_uri ;\n"
                + "                     chembl:type ?std_type;\n"
                + "                     chembl:relation ?relation;\n"
                + "                     chembl:standardValue ?std_value;\n"
                + "                     chembl:standardUnits ?std_unit;\n"
                + "                     chembl:onAssay ?assay_uri .\n"
                + "                 ?assay_uri chembl:hasTarget ?target_uri .\n"
                + "                 ?target_uri dc:title ?target_name ;\n"
                + "                     chembl:organism ?target_organism .\n"
                + "                 OPTIONAL { "
                + "                     ?chembl_uri sio:CHEMINF_000200 ?bNode1 .\n"
                + "                     ?bNode1 a sio:CHEMINF_000198 ;\n"
                + "                         sio:SIO_000300 ?molweight. \n"
                + "                 }\n"
                + "                 OPTIONAL { "
                + "                     ?chembl_uri sio:CHEMINF_000200 ?bNode2 .\n"
                + "                     ?bNode2 a sio:CHEMINF_000314 ;\n"
                + "                         sio:SIO_000300 ?num_ro5_violations. \n"
                + "                 }\n"
                + "                 FILTER (?chembl_uri = <http://data.kasabi.com/dataset/chembl-rdf/molecule/m276734> )\n"
                + "             }\n"
                + "         }\n"
                + "         GROUP BY ?chembl_uri ?item ?std_type ?relation ?std_value ?std_unit ?assay_uri ?bNode1 \n"
                + "                 ?molweight ?bNode2 ?num_ro5_violations ?activity_value  \n"
                + "         ORDER BY ?item   \n"
                + "         LIMIT 10  OFFSET 0 "
                + "     }\n"
                + " }\n";
        queryCase.addParameter("?cw_uri");
        queryCase.addParameter("?cs_uri");
        queryCase.addParameter("?chembl_uri");
        queryCase.addParameter("?db_uri");
        queryCase.insertURI = "http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5";
        queries.put(queryCase.key, queryCase);
    }
   
    private void loadManyWhere() {
        QueryCase queryCase = new QueryCase();
        queryCase.key = "OpsManyWhere";
        queryCase.name = "Query which caused the many where bug";
        queryCase.originalQuery = "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX void: <http://rdfs.org/ns/void#>\n"
                + "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n"
                + "PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>\n"
                + "CONSTRUCT { \n"
                + "     <http://www.conceptwiki.org/concept/00059958-a045-4581-9dc5-e5a08bb0c291> skos:exactMatch ?cw_uri ;\n"
                + "         skos:exactMatch ?chembl_uri ;\n"
                + "         skos:exactMatch ?db_uri .\n"
                + "         ?cw_uri skos:prefLabel ?compound_name ;\n"
                + "         void:inDataset <http://www.conceptwiki.org> .\n"
                + "     ?chembl_uri chembl:hasKeyword ?keywords ;\n"
                + "         chembl:hasDescription ?description ;\n"
                + "         rdfs:subClassOf ?target_type ;\n"
                + "         chembl:organism ?organism ;\n"
                + "         rdfs:label ?synonyms ;	\n"
                + "         void:inDataset <http://data.kasabi.com/dataset/chembl-rdf>.\n"
                + "     ?db_uri drugbank:cellularLocation ?cellularLocation ;\n"
                + "         drugbank:molecularWeight ?molecularWeight ;\n"
                + "         drugbank:numberOfResidues ?numberOfResidues ;\n"
                + "         drugbank:pdbIdPage ?pdbIdPage ;\n"
                + "         drugbank:specificFunction ?specificFunction ;\n"
                + "         drugbank:theoreticalPi ?theoreticalPi .\n"
                + "}\n"
                + "WHERE { \n"
                + "     GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "         ?cw_uri skos:prefLabel ?target_name.\n"
                + "     }\n"
                + "     {\n"
                + "         SELECT ?target_type ?description ?organism \n"
                + "                 (GROUP_CONCAT( DISTINCT ?keyword ; SEPARATOR=' , ') as ?keywords ) \n"
                + "                 (GROUP_CONCAT( DISTINCT ?synonym ; SEPARATOR=' , ' ) as ?synonyms) {\n"
                + "             GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "                 ?chembl_uri chembl:hasKeyword ?keyword ;\n"
                + "                     chembl:hasDescription ?description ;\n"
                + "                     rdfs:subClassOf ?target_type ;\n"
                + "                     chembl:organism ?organism ;\n"
                + "                 rdfs:label ?synonym\n"
                + "             }\n"
                + "         } \n"
                + "         GROUP BY ?target_type ?description ?organism ?molecularWeight ?numberOfResidues  \n"
                + "     }\n"
                + "     {\n"
                + "         SELECT ?molecularWeight ?numberOfResidues ?pdbIdPage ?specificFunction ?theoreticalPi \n"
                + "                 (GROUP_CONCAT( DISTINCT ?cellularLocation ; SEPARATOR=' , ' ) as ?cellularLocations ) {\n"
                + "             GRAPH <http://linkedlifedata.com/resource/drugbank> {\n"
                + "                 OPTIONAL { ?db_uri drugbank:cellularLocation ?cellularLocation }\n"
                + "                 OPTIONAL { ?db_uri drugbank:molecularWeight ?molecularWeight }\n"
                + "                 OPTIONAL { ?db_uri drugbank:numberOfResidues ?numberOfResidues }\n"
                + "                 OPTIONAL { ?db_uri drugbank:pdbIdPage ?pdbIdPage }\n"
                + "                 OPTIONAL { ?db_uri drugbank:specificFunction ?specificFunction }\n"
                + "                 OPTIONAL { ?db_uri drugbank:theoreticalPi ?theoreticalPi }\n"
                + "             }\n"
                + "         }\n"
                + "         GROUP BY ?molecularWeight ?numberOfResidues ?pdbIdPage ?specificFunction ?theoreticalPi \n"
                + "     }\n"
                + "} LIMIT 100";
        queryCase.replaceQuery = "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX void: <http://rdfs.org/ns/void#>\n"
                + "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n"
                + "PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>\n"
                + "CONSTRUCT { \n"
                + "     <http://www.conceptwiki.org/concept/00059958-a045-4581-9dc5-e5a08bb0c291> skos:exactMatch ?cw_uri ;\n"
                + "         skos:exactMatch ?chembl_uri ;\n"
                + "         skos:exactMatch ?db_uri .\n"
                + "         ?cw_uri skos:prefLabel ?compound_name ;\n"
                + "         void:inDataset <http://www.conceptwiki.org> .\n"
                + "     ?chembl_uri chembl:hasKeyword ?keywords ;\n"
                + "         chembl:hasDescription ?description ;\n"
                + "         rdfs:subClassOf ?target_type ;\n"
                + "         chembl:organism ?organism ;\n"
                + "         rdfs:label ?synonyms ;	\n"
                + "         void:inDataset <http://data.kasabi.com/dataset/chembl-rdf>.\n"
                + "     ?db_uri drugbank:cellularLocation ?cellularLocation ;\n"
                + "         drugbank:molecularWeight ?molecularWeight ;\n"
                + "         drugbank:numberOfResidues ?numberOfResidues ;\n"
                + "         drugbank:pdbIdPage ?pdbIdPage ;\n"
                + "         drugbank:specificFunction ?specificFunction ;\n"
                + "         drugbank:theoreticalPi ?theoreticalPi .\n"
                + "}\n"
                + "WHERE { \n"
                + "     GRAPH <http://larkc.eu#Fixedcontext> {\n"
                + "         ?cw_uri skos:prefLabel ?target_name.\n"
                + "     FILTER (?cw_uri = <http://www.conceptwiki.org/concept/516c9a26-885c-4920-9a13-d0a68cf99084>)\n"
                + "     }\n"
                + "     {\n"
                + "         SELECT ?target_type ?description ?organism \n"
                + "                 (GROUP_CONCAT( DISTINCT ?keyword ; SEPARATOR=' , ') as ?keywords ) \n"
                + "                 (GROUP_CONCAT( DISTINCT ?synonym ; SEPARATOR=' , ' ) as ?synonyms) {\n"
                + "             GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "                 ?chembl_uri chembl:hasKeyword ?keyword ;\n"
                + "                     chembl:hasDescription ?description ;\n"
                + "                     rdfs:subClassOf ?target_type ;\n"
                + "                     chembl:organism ?organism ;\n"
                + "                 rdfs:label ?synonym\n"
                + "                 FILTER (?chembl_uri = <http://data.kasabi.com/dataset/chembl-rdf/target/t11063>)\n"
                + "             }\n"
                + "         } \n"
                + "         GROUP BY ?target_type ?description ?organism ?molecularWeight ?numberOfResidues  \n"
                + "     }\n"
                + "     {\n"
                + "         SELECT ?molecularWeight ?numberOfResidues ?pdbIdPage ?specificFunction ?theoreticalPi \n"
                + "                 (GROUP_CONCAT( DISTINCT ?cellularLocation ; SEPARATOR=' , ' ) as ?cellularLocations ) {\n"
                + "             GRAPH <http://linkedlifedata.com/resource/drugbank> {\n"
                + "                 OPTIONAL { ?db_uri drugbank:cellularLocation ?cellularLocation }\n"
                + "                 OPTIONAL { ?db_uri drugbank:molecularWeight ?molecularWeight }\n"
                + "                 OPTIONAL { ?db_uri drugbank:numberOfResidues ?numberOfResidues }\n"
                + "                 OPTIONAL { ?db_uri drugbank:pdbIdPage ?pdbIdPage }\n"
                + "                 OPTIONAL { ?db_uri drugbank:specificFunction ?specificFunction }\n"
                + "                 OPTIONAL { ?db_uri drugbank:theoreticalPi ?theoreticalPi }\n"
                + "                 FILTER (?db_uri = <http://www4.wiwiss.fu-berlin.de/drugbank/resource/targets/6131>)\n"
                + "             }\n"
                + "         }\n"
                + "         GROUP BY ?molecularWeight ?numberOfResidues ?pdbIdPage ?specificFunction ?theoreticalPi \n"
                + "     }\n"
                + "} LIMIT 100";
        queryCase.addParameter("?cw_uri");
        queryCase.addParameter("?cs_uri");
        queryCase.addParameter("?chembl_uri");
        queryCase.addParameter("?db_uri");
        queryCase.insertURI = "http://www.conceptwiki.org/concept/516c9a26-885c-4920-9a13-d0a68cf99084";
        queries.put(queryCase.key, queryCase);
    }

    private void loadCurlyBrackBug() {
        QueryCase queryCase = new QueryCase();
        queryCase.key = "OpsReplacementCurlyBrackBug";
        queryCase.name = "Query which cuased the curly bracket bug";
        queryCase.originalQuery = "PREFIX ops: <http://www.openphacts.org/api#>\n"
                + "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX void: <http://rdfs.org/ns/void#>\n"
                + "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX chemspider: <http://rdf.chemspider.com/#>\n"
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n"
                + "PREFIX owl: <http://www.w3.org/2002/07/owl#>\n"
                + "PREFIX sio: <http://semanticscience.org/resource/>\n"
                + "CONSTRUCT { \n"
                + "     [] ops:input <http://www.conceptwiki.org/concept/00059958-a045-4581-9dc5-e5a08bb0c291> .\n"
                + "     ?item chembl:forMolecule ?compound_chembl;\n"
                + "         chembl:type ?std_type;\n"
                + "         chembl:relation ?relation;\n"
                + "         chembl:standardValue ?std_value;\n"
                + "         chembl:standardUnits ?std_unit;\n"
                + "         chembl:onAssay ?assay_uri ;\n"
                + "         void:inDataset <http://data.kasabi.com/dataset/chembl-rdf> .\n"
                + "     ?assay_uri chembl:hasTarget ?chembl_uri ;\n"
                + "         chembl:organism ?assay_organism .\n"
                + "     ?chembl_uri chembl:organism ?target_organism ;\n"
                + "         skos:prefLabel ?target_name ;\n"
                + "         void:inDataset <http://www.conceptwiki.org/> .\n"
                + "     ?compound_chembl ?node1 ?num_ro5_violations ;\n"
                + "     	?node2 ?molweight ;\n"
                + "     	skos:exactMatch ?compound_cs ;\n"
                + "     	skos:exactMatch ?compound_cw ;\n"
                + "     	void:inDataset <http://data.kasabi.com/dataset/chembl-rdf> .\n"
                + "     ?compound_cs chemspider:smiles ?smiles ;\n"
                + "     	chemspider:inchi ?inchi ;\n"
                + "     	chemspider:inchikey ?inchiKey;\n"
                + "     	void:inDataset <http://rdf.chemspider.com/> .\n"
                + "     ?compound_cw skos:prefLabel ?compound_name ;\n"
                + "     	void:inDataset <http://www.conceptwiki.org/> .\n"
                + "}\n"
                + "WHERE {\n"
                + "     SELECT DISTINCT ?item ?chembl_uri ?compound_chembl ?compound_cs ?inchi ?inchi_key ?smiles \n"
                + "             ?compound_name ?target_name ?target_organism ?std_type ?relation ?std_value ?std_unit \n"
                + "             ?assay_uri ?assay_organism ?node1 ?molweight ?node2 ?num_ro5_violations {\n"
                + "         GRAPH <http://purl.uniprot.org/enzyme/inference> {\n"
                + "             ?subclass rdfs:subClassOf <http://www.conceptwiki.org/concept/00059958-a045-4581-9dc5-e5a08bb0c291> \n"
                + "         }	\n"
                + "         GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "             ?chembl_uri chembl:organism ?target_organism . \n"
                + "             ?assay_uri chembl:hasTarget ?chembl_uri ;\n"
                + "                 chembl:organism ?target_organism .\n"
                + "                 ?item chembl:onAssay ?assay_uri ;\n"
                + "                 chembl:type ?std_type ;\n"
                + "                 chembl:relation ?relation ;\n"
                + "                 chembl:standardValue ?std_value ;\n"
                + "                 chembl:standardUnits ?std_unit ;\n"
                + "                 chembl:forMolecule ?compound_chembl ;\n"
                + "                 chembl:organism ?assay_organism .\n"
                + "             ?compound_chembl owl:equivalentClass ?equiv_uri . \n"
                + "               	?equiv_uri skos:exactMatch ?compound_cs .\n"
                + "             OPTIONAL {\n"
                + "                 ?compound_chembl sio:CHEMINF_000200 ?node1 . \n"
                + "                 ?node1 a sio:CHEMINF_000314 ;\n"
                + "                     sio:SIO_000300 ?num_ro5_violations \n"
                + "             }\n"
                + "             OPTIONAL { \n"
                + "                 ?compound_chembl sio:CHEMINF_000200 ?node2 . \n"
                + "                     ?node2 a sio:CHEMINF_000198 ;\n"
                + "                     sio:SIO_000300 ?molweight \n"
                + "             }\n"
                + "         }\n"
                + "         GRAPH <http://www.chemspider.com> {\n"
                + "             ?compound_cs chemspider:inchi ?inchi;\n"
                + "                 chemspider:inchikey ?inchi_key;\n"
                + "                 chemspider:smiles ?smiles . \n"
                + "         }\n"
                + "         GRAPH <http://www.conceptwiki.org> {\n"
                + "             ?cw_uri skos:prefLabel ?target_name .\n"
                + "             ?compound_cw skos:exactMatch ?compound_cs ; \n"
                + "                 skos:prefLabel ?compound_name .\n"
                + "         }\n"
                + "     } \n"
                + "     ORDER BY ?item \n"
                + "     LIMIT 10  OFFSET 0 \n"
                + "}";
        queryCase.replaceQuery = "PREFIX ops: <http://www.openphacts.org/api#>\n"
                + "PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>\n"
                + "PREFIX void: <http://rdfs.org/ns/void#>\n"
                + "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n"
                + "PREFIX chemspider: <http://rdf.chemspider.com/#>\n"
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n"
                + "PREFIX owl: <http://www.w3.org/2002/07/owl#>\n"
                + "PREFIX sio: <http://semanticscience.org/resource/>\n"
                + "CONSTRUCT { \n"
                + "     [] ops:input <http://www.conceptwiki.org/concept/00059958-a045-4581-9dc5-e5a08bb0c291> .\n"
                + "     ?item chembl:forMolecule ?compound_chembl;\n"
                + "         chembl:type ?std_type;\n"
                + "         chembl:relation ?relation;\n"
                + "         chembl:standardValue ?std_value;\n"
                + "         chembl:standardUnits ?std_unit;\n"
                + "         chembl:onAssay ?assay_uri ;\n"
                + "         void:inDataset <http://data.kasabi.com/dataset/chembl-rdf> .\n"
                + "     ?assay_uri chembl:hasTarget ?chembl_uri ;\n"
                + "         chembl:organism ?assay_organism .\n"
                + "     ?chembl_uri chembl:organism ?target_organism ;\n"
                + "         skos:prefLabel ?target_name ;\n"
                + "         void:inDataset <http://www.conceptwiki.org/> .\n"
                + "     ?compound_chembl ?node1 ?num_ro5_violations ;\n"
                + "     	?node2 ?molweight ;\n"
                + "     	skos:exactMatch ?compound_cs ;\n"
                + "     	skos:exactMatch ?compound_cw ;\n"
                + "     	void:inDataset <http://data.kasabi.com/dataset/chembl-rdf> .\n"
                + "     ?compound_cs chemspider:smiles ?smiles ;\n"
                + "     	chemspider:inchi ?inchi ;\n"
                + "     	chemspider:inchikey ?inchiKey;\n"
                + "     	void:inDataset <http://rdf.chemspider.com/> .\n"
                + "     ?compound_cw skos:prefLabel ?compound_name ;\n"
                + "     	void:inDataset <http://www.conceptwiki.org/> .\n"
                + "}\n"
                + "WHERE {\n"
                + "     SELECT DISTINCT ?item ?chembl_uri ?compound_chembl ?compound_cs ?inchi ?inchi_key ?smiles \n"
                + "             ?compound_name ?target_name ?target_organism ?std_type ?relation ?std_value ?std_unit \n"
                + "             ?assay_uri ?assay_organism ?node1 ?molweight ?node2 ?num_ro5_violations {\n"
                + "         GRAPH <http://purl.uniprot.org/enzyme/inference> {\n"
                + "             ?subclass rdfs:subClassOf <http://www.conceptwiki.org/concept/00059958-a045-4581-9dc5-e5a08bb0c291> \n"
                + "         }	\n"
                + "         GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {\n"
                + "             ?chembl_uri chembl:organism ?target_organism . \n"
                + "             ?assay_uri chembl:hasTarget ?chembl_uri ;\n"
                + "                 chembl:organism ?target_organism .\n"
                + "                 ?item chembl:onAssay ?assay_uri ;\n"
                + "                 chembl:type ?std_type ;\n"
                + "                 chembl:relation ?relation ;\n"
                + "                 chembl:standardValue ?std_value ;\n"
                + "                 chembl:standardUnits ?std_unit ;\n"
                + "                 chembl:forMolecule ?compound_chembl ;\n"
                + "                 chembl:organism ?assay_organism .\n"
                + "             ?compound_chembl owl:equivalentClass ?equiv_uri . \n"
                + "               	?equiv_uri skos:exactMatch ?compound_cs .\n"
                + "             OPTIONAL {\n"
                + "                 ?compound_chembl sio:CHEMINF_000200 ?node1 . \n"
                + "                 ?node1 a sio:CHEMINF_000314 ;\n"
                + "                     sio:SIO_000300 ?num_ro5_violations \n"
                + "             }\n"
                + "             OPTIONAL { \n"
                + "                 ?compound_chembl sio:CHEMINF_000200 ?node2 . \n"
                + "                     ?node2 a sio:CHEMINF_000198 ;\n"
                + "                     sio:SIO_000300 ?molweight \n"
                + "             }\n"
                + "             FILTER (?chembl_uri = <http://data.kasabi.com/dataset/chembl-rdf/molecule/m276734> \n"
                + "                  || ?chembl_uri = <http://data.kasabi.com/dataset/chembl-rdf/target/t197>)\n"
                + "         }\n"
                + "         GRAPH <http://www.chemspider.com> {\n"
                + "             ?compound_cs chemspider:inchi ?inchi;\n"
                + "                 chemspider:inchikey ?inchi_key;\n"
                + "                 chemspider:smiles ?smiles . \n"
                + "         }\n"
                + "         GRAPH <http://www.conceptwiki.org> {\n"
                + "             ?cw_uri skos:prefLabel ?target_name .\n"
                + "             ?compound_cw skos:exactMatch ?compound_cs ; \n"
                + "                 skos:prefLabel ?compound_name .\n"
                + "             FILTER (?cw_uri = <http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5>)\n"
                + "         }\n"
                + "     } \n"
                + "     ORDER BY ?item \n"
                + "     LIMIT 10  OFFSET 0 \n"
                + "}";
        queryCase.addParameter("?cw_uri");
        queryCase.addParameter("?chembl_uri");
        queryCase.insertURI = "http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5";
        queries.put(queryCase.key, queryCase);
    }

    private void load() {
        QueryCase queryCase = new QueryCase();
        queryCase.key = "OpsReplacement";
        queryCase.name = " Query";
        queryCase.originalQuery = "";
        queries.put(queryCase.key, queryCase);
    }
}
